// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DisasterLocation struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Latitude  float64            `json:"latitude"`
	Longitude float64            `json:"longitude"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
	CreatedBy string             `json:"createdBy"`
}

type DomainEvent struct {
	ID            uuid.UUID          `json:"id"`
	AggregateType string             `json:"aggregateType"`
	AggregateID   uuid.UUID          `json:"aggregateId"`
	EventType     string             `json:"eventType"`
	SchemaVersion int32              `json:"schemaVersion"`
	Payload       []byte             `json:"payload"`
	ActorSub      string             `json:"actorSub"`
	OccurredAt    pgtype.Timestamptz `json:"occurredAt"`
	PublishedAt   pgtype.Timestamptz `json:"publishedAt"`
}

type LocationStat struct {
	LocationID    uuid.UUID          `json:"locationId"`
	GoodCount     int32              `json:"goodCount"`
	ModerateCount int32              `json:"moderateCount"`
	BadCount      int32              `json:"badCount"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
}

type Photo struct {
	ID               uuid.UUID          `json:"id"`
	SiteAssessmentID uuid.UUID          `json:"siteAssessmentId"`
	S3Key            string             `json:"s3Key"`
	Latitude         float64            `json:"latitude"`
	Longitude        float64            `json:"longitude"`
	Condition        string             `json:"condition"`
	CreatedAt        pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt        pgtype.Timestamptz `json:"updatedAt"`
	CreatedBy        string             `json:"createdBy"`
}

type ProcessedEvent struct {
	EventID      uuid.UUID          `json:"eventId"`
	ConsumerName string             `json:"consumerName"`
	ProcessedAt  pgtype.Timestamptz `json:"processedAt"`
}

type SiteAssessment struct {
	ID         uuid.UUID          `json:"id"`
	LocationID uuid.UUID          `json:"locationId"`
	Name       string             `json:"name"`
	Notes      string             `json:"notes"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt  pgtype.Timestamptz `json:"updatedAt"`
	CreatedBy  string             `json:"createdBy"`
}

type WsConnection struct {
	ConnectionID string             `json:"connectionId"`
	UserSub      string             `json:"userSub"`
	LocationID   uuid.UUID          `json:"locationId"`
	ConnectedAt  pgtype.Timestamptz `json:"connectedAt"`
}
