// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountPhotosByConditionForLocation(ctx context.Context, locationID uuid.UUID) ([]CountPhotosByConditionForLocationRow, error)
	CountPhotosBySite(ctx context.Context, siteAssessmentID uuid.UUID) (int64, error)
	DeleteWSConnection(ctx context.Context, connectionID string) error
	GetLocation(ctx context.Context, id uuid.UUID) (DisasterLocation, error)
	GetLocationStats(ctx context.Context, locationID uuid.UUID) (LocationStat, error)
	GetPhoto(ctx context.Context, id uuid.UUID) (Photo, error)
	GetSiteAssessment(ctx context.Context, id uuid.UUID) (SiteAssessment, error)
	InsertDomainEvent(ctx context.Context, arg InsertDomainEventParams) (DomainEvent, error)
	InsertWSConnection(ctx context.Context, arg InsertWSConnectionParams) error
	IsEventProcessed(ctx context.Context, arg IsEventProcessedParams) (bool, error)
	ListPhotosBySite(ctx context.Context, siteAssessmentID uuid.UUID) ([]Photo, error)
	ListSiteAssessmentsByLocation(ctx context.Context, locationID uuid.UUID) ([]SiteAssessment, error)
	// Idempotency lives here: an event already recorded in processed_events for
	// this consumer_name is excluded by the LEFT JOIN, so a redelivered event
	// (EventBridge/SQS are at-least-once) is simply never selected again.
	ListUnprocessedEventsForConsumer(ctx context.Context, arg ListUnprocessedEventsForConsumerParams) ([]DomainEvent, error)
	ListUnpublishedEvents(ctx context.Context, limit int32) ([]DomainEvent, error)
	ListWSConnectionsByLocation(ctx context.Context, locationID uuid.UUID) ([]WsConnection, error)
	MarkEventProcessed(ctx context.Context, arg MarkEventProcessedParams) error
	MarkEventPublished(ctx context.Context, id uuid.UUID) error
	// Atomic LWW upsert: applies iff new, or existing row is strictly older.
	// Returns 0 rows (pgx.ErrNoRows) when blocked — the service falls back to
	// GetLocation to classify ignored-stale vs. conflict (equal timestamps).
	UpsertLocation(ctx context.Context, arg UpsertLocationParams) (DisasterLocation, error)
	UpsertLocationStats(ctx context.Context, arg UpsertLocationStatsParams) error
	// Atomic LWW upsert *and* the <=10-photos-per-site rule in one round trip:
	// the source SELECT only yields a row when the photo already exists (update
	// path, uncapped) or the site is still under the cap (insert path) — so a
	// new photo past the cap contributes no row, the INSERT is a no-op, and
	// ON CONFLICT never fires. That makes the cap check and the id-conflict
	// check race-free without an explicit transaction or row lock: the whole
	// decision happens inside one statement.
	UpsertPhoto(ctx context.Context, arg UpsertPhotoParams) (Photo, error)
	// Same atomic LWW pattern as UpsertLocation.
	UpsertSiteAssessment(ctx context.Context, arg UpsertSiteAssessmentParams) (SiteAssessment, error)
}

var _ Querier = (*Queries)(nil)
