// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPhotosByConditionForLocation = `-- name: CountPhotosByConditionForLocation :many
SELECT p.condition, count(*) AS count
FROM photos p
JOIN site_assessments s ON s.id = p.site_assessment_id
WHERE s.location_id = $1
GROUP BY p.condition
`

type CountPhotosByConditionForLocationRow struct {
	Condition string `json:"condition"`
	Count     int64  `json:"count"`
}

func (q *Queries) CountPhotosByConditionForLocation(ctx context.Context, locationID uuid.UUID) ([]CountPhotosByConditionForLocationRow, error) {
	rows, err := q.db.Query(ctx, countPhotosByConditionForLocation, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountPhotosByConditionForLocationRow
	for rows.Next() {
		var i CountPhotosByConditionForLocationRow
		if err := rows.Scan(&i.Condition, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPhotosBySite = `-- name: CountPhotosBySite :one
SELECT count(*) FROM photos WHERE site_assessment_id = $1
`

func (q *Queries) CountPhotosBySite(ctx context.Context, siteAssessmentID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPhotosBySite, siteAssessmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteWSConnection = `-- name: DeleteWSConnection :exec
DELETE FROM ws_connections WHERE connection_id = $1
`

func (q *Queries) DeleteWSConnection(ctx context.Context, connectionID string) error {
	_, err := q.db.Exec(ctx, deleteWSConnection, connectionID)
	return err
}

const getLocation = `-- name: GetLocation :one
SELECT id, name, latitude, longitude, created_at, updated_at, created_by FROM disaster_locations WHERE id = $1
`

func (q *Queries) GetLocation(ctx context.Context, id uuid.UUID) (DisasterLocation, error) {
	row := q.db.QueryRow(ctx, getLocation, id)
	var i DisasterLocation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getLocationStats = `-- name: GetLocationStats :one
SELECT location_id, good_count, moderate_count, bad_count, updated_at FROM location_stats WHERE location_id = $1
`

func (q *Queries) GetLocationStats(ctx context.Context, locationID uuid.UUID) (LocationStat, error) {
	row := q.db.QueryRow(ctx, getLocationStats, locationID)
	var i LocationStat
	err := row.Scan(
		&i.LocationID,
		&i.GoodCount,
		&i.ModerateCount,
		&i.BadCount,
		&i.UpdatedAt,
	)
	return i, err
}

const getPhoto = `-- name: GetPhoto :one
SELECT id, site_assessment_id, s3_key, latitude, longitude, condition, created_at, updated_at, created_by FROM photos WHERE id = $1
`

func (q *Queries) GetPhoto(ctx context.Context, id uuid.UUID) (Photo, error) {
	row := q.db.QueryRow(ctx, getPhoto, id)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.SiteAssessmentID,
		&i.S3Key,
		&i.Latitude,
		&i.Longitude,
		&i.Condition,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getSiteAssessment = `-- name: GetSiteAssessment :one
SELECT id, location_id, name, notes, created_at, updated_at, created_by FROM site_assessments WHERE id = $1
`

func (q *Queries) GetSiteAssessment(ctx context.Context, id uuid.UUID) (SiteAssessment, error) {
	row := q.db.QueryRow(ctx, getSiteAssessment, id)
	var i SiteAssessment
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Name,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const insertDomainEvent = `-- name: InsertDomainEvent :one
INSERT INTO domain_events (aggregate_type, aggregate_id, event_type, schema_version, payload, actor_sub)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, aggregate_type, aggregate_id, event_type, schema_version, payload, actor_sub, occurred_at, published_at
`

type InsertDomainEventParams struct {
	AggregateType string    `json:"aggregateType"`
	AggregateID   uuid.UUID `json:"aggregateId"`
	EventType     string    `json:"eventType"`
	SchemaVersion int32     `json:"schemaVersion"`
	Payload       []byte    `json:"payload"`
	ActorSub      string    `json:"actorSub"`
}

func (q *Queries) InsertDomainEvent(ctx context.Context, arg InsertDomainEventParams) (DomainEvent, error) {
	row := q.db.QueryRow(ctx, insertDomainEvent,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.SchemaVersion,
		arg.Payload,
		arg.ActorSub,
	)
	var i DomainEvent
	err := row.Scan(
		&i.ID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.SchemaVersion,
		&i.Payload,
		&i.ActorSub,
		&i.OccurredAt,
		&i.PublishedAt,
	)
	return i, err
}

const insertWSConnection = `-- name: InsertWSConnection :exec
INSERT INTO ws_connections (connection_id, user_sub, location_id) VALUES ($1, $2, $3)
`

type InsertWSConnectionParams struct {
	ConnectionID string    `json:"connectionId"`
	UserSub      string    `json:"userSub"`
	LocationID   uuid.UUID `json:"locationId"`
}

func (q *Queries) InsertWSConnection(ctx context.Context, arg InsertWSConnectionParams) error {
	_, err := q.db.Exec(ctx, insertWSConnection, arg.ConnectionID, arg.UserSub, arg.LocationID)
	return err
}

const isEventProcessed = `-- name: IsEventProcessed :one
SELECT EXISTS(SELECT 1 FROM processed_events WHERE event_id = $1 AND consumer_name = $2)
`

type IsEventProcessedParams struct {
	EventID      uuid.UUID `json:"eventId"`
	ConsumerName string    `json:"consumerName"`
}

func (q *Queries) IsEventProcessed(ctx context.Context, arg IsEventProcessedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isEventProcessed, arg.EventID, arg.ConsumerName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listPhotosBySite = `-- name: ListPhotosBySite :many
SELECT id, site_assessment_id, s3_key, latitude, longitude, condition, created_at, updated_at, created_by FROM photos WHERE site_assessment_id = $1 ORDER BY created_at
`

func (q *Queries) ListPhotosBySite(ctx context.Context, siteAssessmentID uuid.UUID) ([]Photo, error) {
	rows, err := q.db.Query(ctx, listPhotosBySite, siteAssessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Photo
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.SiteAssessmentID,
			&i.S3Key,
			&i.Latitude,
			&i.Longitude,
			&i.Condition,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteAssessmentsByLocation = `-- name: ListSiteAssessmentsByLocation :many
SELECT id, location_id, name, notes, created_at, updated_at, created_by FROM site_assessments WHERE location_id = $1 ORDER BY created_at
`

func (q *Queries) ListSiteAssessmentsByLocation(ctx context.Context, locationID uuid.UUID) ([]SiteAssessment, error) {
	rows, err := q.db.Query(ctx, listSiteAssessmentsByLocation, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SiteAssessment
	for rows.Next() {
		var i SiteAssessment
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.Name,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnprocessedEventsForConsumer = `-- name: ListUnprocessedEventsForConsumer :many
SELECT de.id, de.aggregate_type, de.aggregate_id, de.event_type, de.schema_version, de.payload, de.actor_sub, de.occurred_at, de.published_at
FROM domain_events de
LEFT JOIN processed_events pe ON pe.event_id = de.id AND pe.consumer_name = $1
WHERE pe.event_id IS NULL AND de.event_type = ANY($3::text[])
ORDER BY de.occurred_at
LIMIT $2
`

type ListUnprocessedEventsForConsumerParams struct {
	ConsumerName string   `json:"consumerName"`
	Limit        int32    `json:"limit"`
	EventTypes   []string `json:"eventTypes"`
}

// Idempotency lives here: an event already recorded in processed_events for
// this consumer_name is excluded by the LEFT JOIN, so a redelivered event
// (EventBridge/SQS are at-least-once) is simply never selected again.
func (q *Queries) ListUnprocessedEventsForConsumer(ctx context.Context, arg ListUnprocessedEventsForConsumerParams) ([]DomainEvent, error) {
	rows, err := q.db.Query(ctx, listUnprocessedEventsForConsumer, arg.ConsumerName, arg.Limit, arg.EventTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DomainEvent
	for rows.Next() {
		var i DomainEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.SchemaVersion,
			&i.Payload,
			&i.ActorSub,
			&i.OccurredAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnpublishedEvents = `-- name: ListUnpublishedEvents :many
SELECT id, aggregate_type, aggregate_id, event_type, schema_version, payload, actor_sub, occurred_at, published_at FROM domain_events WHERE published_at IS NULL ORDER BY occurred_at LIMIT $1
`

func (q *Queries) ListUnpublishedEvents(ctx context.Context, limit int32) ([]DomainEvent, error) {
	rows, err := q.db.Query(ctx, listUnpublishedEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DomainEvent
	for rows.Next() {
		var i DomainEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.SchemaVersion,
			&i.Payload,
			&i.ActorSub,
			&i.OccurredAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWSConnectionsByLocation = `-- name: ListWSConnectionsByLocation :many
SELECT connection_id, user_sub, location_id, connected_at FROM ws_connections WHERE location_id = $1
`

func (q *Queries) ListWSConnectionsByLocation(ctx context.Context, locationID uuid.UUID) ([]WsConnection, error) {
	rows, err := q.db.Query(ctx, listWSConnectionsByLocation, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WsConnection
	for rows.Next() {
		var i WsConnection
		if err := rows.Scan(
			&i.ConnectionID,
			&i.UserSub,
			&i.LocationID,
			&i.ConnectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventProcessed = `-- name: MarkEventProcessed :exec
INSERT INTO processed_events (event_id, consumer_name) VALUES ($1, $2)
ON CONFLICT (event_id, consumer_name) DO NOTHING
`

type MarkEventProcessedParams struct {
	EventID      uuid.UUID `json:"eventId"`
	ConsumerName string    `json:"consumerName"`
}

func (q *Queries) MarkEventProcessed(ctx context.Context, arg MarkEventProcessedParams) error {
	_, err := q.db.Exec(ctx, markEventProcessed, arg.EventID, arg.ConsumerName)
	return err
}

const markEventPublished = `-- name: MarkEventPublished :exec
UPDATE domain_events SET published_at = now() WHERE id = $1
`

func (q *Queries) MarkEventPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEventPublished, id)
	return err
}

const upsertLocation = `-- name: UpsertLocation :one
INSERT INTO disaster_locations (id, name, latitude, longitude, created_at, updated_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    updated_at = EXCLUDED.updated_at
WHERE EXCLUDED.updated_at > disaster_locations.updated_at
RETURNING id, name, latitude, longitude, created_at, updated_at, created_by
`

type UpsertLocationParams struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Latitude  float64            `json:"latitude"`
	Longitude float64            `json:"longitude"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
	CreatedBy string             `json:"createdBy"`
}

// Atomic LWW upsert: applies iff new, or existing row is strictly older.
// Returns 0 rows (pgx.ErrNoRows) when blocked — the service falls back to
// GetLocation to classify ignored-stale vs. conflict (equal timestamps).
func (q *Queries) UpsertLocation(ctx context.Context, arg UpsertLocationParams) (DisasterLocation, error) {
	row := q.db.QueryRow(ctx, upsertLocation,
		arg.ID,
		arg.Name,
		arg.Latitude,
		arg.Longitude,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedBy,
	)
	var i DisasterLocation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const upsertLocationStats = `-- name: UpsertLocationStats :exec
INSERT INTO location_stats (location_id, good_count, moderate_count, bad_count, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (location_id) DO UPDATE SET
    good_count     = EXCLUDED.good_count,
    moderate_count = EXCLUDED.moderate_count,
    bad_count      = EXCLUDED.bad_count,
    updated_at     = now()
`

type UpsertLocationStatsParams struct {
	LocationID    uuid.UUID `json:"locationId"`
	GoodCount     int32     `json:"goodCount"`
	ModerateCount int32     `json:"moderateCount"`
	BadCount      int32     `json:"badCount"`
}

func (q *Queries) UpsertLocationStats(ctx context.Context, arg UpsertLocationStatsParams) error {
	_, err := q.db.Exec(ctx, upsertLocationStats,
		arg.LocationID,
		arg.GoodCount,
		arg.ModerateCount,
		arg.BadCount,
	)
	return err
}

const upsertPhoto = `-- name: UpsertPhoto :one
INSERT INTO photos (id, site_assessment_id, s3_key, latitude, longitude, condition, created_at, updated_at, created_by)
SELECT
    $1::uuid,
    $2::uuid,
    $3::text,
    $4::float8,
    $5::float8,
    $6::text,
    $7::timestamptz,
    $8::timestamptz,
    $9::text
WHERE EXISTS (SELECT 1 FROM photos WHERE id = $1)
   OR (SELECT count(*) FROM photos WHERE site_assessment_id = $2) < 10
ON CONFLICT (id) DO UPDATE SET
    s3_key = EXCLUDED.s3_key,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    condition = EXCLUDED.condition,
    updated_at = EXCLUDED.updated_at
WHERE EXCLUDED.updated_at > photos.updated_at
RETURNING id, site_assessment_id, s3_key, latitude, longitude, condition, created_at, updated_at, created_by
`

type UpsertPhotoParams struct {
	ID               uuid.UUID          `json:"id"`
	SiteAssessmentID uuid.UUID          `json:"siteAssessmentId"`
	S3Key            string             `json:"s3Key"`
	Latitude         float64            `json:"latitude"`
	Longitude        float64            `json:"longitude"`
	Condition        string             `json:"condition"`
	CreatedAt        pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt        pgtype.Timestamptz `json:"updatedAt"`
	CreatedBy        string             `json:"createdBy"`
}

// Atomic LWW upsert *and* the <=10-photos-per-site rule in one round trip:
// the source SELECT only yields a row when the photo already exists (update
// path, uncapped) or the site is still under the cap (insert path) — so a
// new photo past the cap contributes no row, the INSERT is a no-op, and
// ON CONFLICT never fires. That makes the cap check and the id-conflict
// check race-free without an explicit transaction or row lock: the whole
// decision happens inside one statement.
func (q *Queries) UpsertPhoto(ctx context.Context, arg UpsertPhotoParams) (Photo, error) {
	row := q.db.QueryRow(ctx, upsertPhoto,
		arg.ID,
		arg.SiteAssessmentID,
		arg.S3Key,
		arg.Latitude,
		arg.Longitude,
		arg.Condition,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedBy,
	)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.SiteAssessmentID,
		&i.S3Key,
		&i.Latitude,
		&i.Longitude,
		&i.Condition,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const upsertSiteAssessment = `-- name: UpsertSiteAssessment :one
INSERT INTO site_assessments (id, location_id, name, notes, created_at, updated_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    notes = EXCLUDED.notes,
    updated_at = EXCLUDED.updated_at
WHERE EXCLUDED.updated_at > site_assessments.updated_at
RETURNING id, location_id, name, notes, created_at, updated_at, created_by
`

type UpsertSiteAssessmentParams struct {
	ID         uuid.UUID          `json:"id"`
	LocationID uuid.UUID          `json:"locationId"`
	Name       string             `json:"name"`
	Notes      string             `json:"notes"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt  pgtype.Timestamptz `json:"updatedAt"`
	CreatedBy  string             `json:"createdBy"`
}

// Same atomic LWW pattern as UpsertLocation.
func (q *Queries) UpsertSiteAssessment(ctx context.Context, arg UpsertSiteAssessmentParams) (SiteAssessment, error) {
	row := q.db.QueryRow(ctx, upsertSiteAssessment,
		arg.ID,
		arg.LocationID,
		arg.Name,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedBy,
	)
	var i SiteAssessment
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Name,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}
