// Code generated by MockGen. DO NOT EDIT.
// Source: internal/db/querier.go
//
// Generated by this command:
//
//	mockgen -source=internal/db/querier.go -destination=internal/inventory/mocks/querier_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	db "ticketing/internal/db"

	uuid "github.com/google/uuid"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// AcquireHold mocks base method.
func (m *MockQuerier) AcquireHold(ctx context.Context, arg db.AcquireHoldParams) ([]db.AcquireHoldRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireHold", ctx, arg)
	ret0, _ := ret[0].([]db.AcquireHoldRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcquireHold indicates an expected call of AcquireHold.
func (mr *MockQuerierMockRecorder) AcquireHold(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireHold", reflect.TypeOf((*MockQuerier)(nil).AcquireHold), ctx, arg)
}

// BulkInsertEventSeats mocks base method.
func (m *MockQuerier) BulkInsertEventSeats(ctx context.Context, arg []db.BulkInsertEventSeatsParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkInsertEventSeats", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkInsertEventSeats indicates an expected call of BulkInsertEventSeats.
func (mr *MockQuerierMockRecorder) BulkInsertEventSeats(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkInsertEventSeats", reflect.TypeOf((*MockQuerier)(nil).BulkInsertEventSeats), ctx, arg)
}

// CloseWSConnection mocks base method.
func (m *MockQuerier) CloseWSConnection(ctx context.Context, connectionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseWSConnection", ctx, connectionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseWSConnection indicates an expected call of CloseWSConnection.
func (mr *MockQuerierMockRecorder) CloseWSConnection(ctx, connectionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseWSConnection", reflect.TypeOf((*MockQuerier)(nil).CloseWSConnection), ctx, connectionID)
}

// ConfirmSeats mocks base method.
func (m *MockQuerier) ConfirmSeats(ctx context.Context, arg db.ConfirmSeatsParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmSeats", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmSeats indicates an expected call of ConfirmSeats.
func (mr *MockQuerierMockRecorder) ConfirmSeats(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmSeats", reflect.TypeOf((*MockQuerier)(nil).ConfirmSeats), ctx, arg)
}

// CountAvailableSeats mocks base method.
func (m *MockQuerier) CountAvailableSeats(ctx context.Context, eventID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAvailableSeats", ctx, eventID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAvailableSeats indicates an expected call of CountAvailableSeats.
func (mr *MockQuerierMockRecorder) CountAvailableSeats(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAvailableSeats", reflect.TypeOf((*MockQuerier)(nil).CountAvailableSeats), ctx, eventID)
}

// CountEventSeats mocks base method.
func (m *MockQuerier) CountEventSeats(ctx context.Context, eventID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountEventSeats", ctx, eventID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountEventSeats indicates an expected call of CountEventSeats.
func (mr *MockQuerierMockRecorder) CountEventSeats(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountEventSeats", reflect.TypeOf((*MockQuerier)(nil).CountEventSeats), ctx, eventID)
}

// CreateEvent mocks base method.
func (m *MockQuerier) CreateEvent(ctx context.Context, arg db.CreateEventParams) (db.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvent", ctx, arg)
	ret0, _ := ret[0].(db.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEvent indicates an expected call of CreateEvent.
func (mr *MockQuerierMockRecorder) CreateEvent(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvent", reflect.TypeOf((*MockQuerier)(nil).CreateEvent), ctx, arg)
}

// CreateEventPriceTier mocks base method.
func (m *MockQuerier) CreateEventPriceTier(ctx context.Context, arg db.CreateEventPriceTierParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEventPriceTier", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEventPriceTier indicates an expected call of CreateEventPriceTier.
func (mr *MockQuerierMockRecorder) CreateEventPriceTier(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEventPriceTier", reflect.TypeOf((*MockQuerier)(nil).CreateEventPriceTier), ctx, arg)
}

// CreateOrder mocks base method.
func (m *MockQuerier) CreateOrder(ctx context.Context, arg db.CreateOrderParams) (db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, arg)
	ret0, _ := ret[0].(db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockQuerierMockRecorder) CreateOrder(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockQuerier)(nil).CreateOrder), ctx, arg)
}

// CreateSagaStep mocks base method.
func (m *MockQuerier) CreateSagaStep(ctx context.Context, arg db.CreateSagaStepParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSagaStep", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSagaStep indicates an expected call of CreateSagaStep.
func (mr *MockQuerierMockRecorder) CreateSagaStep(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSagaStep", reflect.TypeOf((*MockQuerier)(nil).CreateSagaStep), ctx, arg)
}

// CreateSeat mocks base method.
func (m *MockQuerier) CreateSeat(ctx context.Context, arg db.CreateSeatParams) (db.Seat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSeat", ctx, arg)
	ret0, _ := ret[0].(db.Seat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSeat indicates an expected call of CreateSeat.
func (mr *MockQuerierMockRecorder) CreateSeat(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSeat", reflect.TypeOf((*MockQuerier)(nil).CreateSeat), ctx, arg)
}

// CreateSeatRow mocks base method.
func (m *MockQuerier) CreateSeatRow(ctx context.Context, arg db.CreateSeatRowParams) (db.SeatRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSeatRow", ctx, arg)
	ret0, _ := ret[0].(db.SeatRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSeatRow indicates an expected call of CreateSeatRow.
func (mr *MockQuerierMockRecorder) CreateSeatRow(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSeatRow", reflect.TypeOf((*MockQuerier)(nil).CreateSeatRow), ctx, arg)
}

// CreateSection mocks base method.
func (m *MockQuerier) CreateSection(ctx context.Context, arg db.CreateSectionParams) (db.Section, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSection", ctx, arg)
	ret0, _ := ret[0].(db.Section)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSection indicates an expected call of CreateSection.
func (mr *MockQuerierMockRecorder) CreateSection(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSection", reflect.TypeOf((*MockQuerier)(nil).CreateSection), ctx, arg)
}

// CreateVenue mocks base method.
func (m *MockQuerier) CreateVenue(ctx context.Context, arg db.CreateVenueParams) (db.Venue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVenue", ctx, arg)
	ret0, _ := ret[0].(db.Venue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVenue indicates an expected call of CreateVenue.
func (mr *MockQuerierMockRecorder) CreateVenue(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVenue", reflect.TypeOf((*MockQuerier)(nil).CreateVenue), ctx, arg)
}

// ExtendHold mocks base method.
func (m *MockQuerier) ExtendHold(ctx context.Context, arg db.ExtendHoldParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtendHold", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtendHold indicates an expected call of ExtendHold.
func (mr *MockQuerierMockRecorder) ExtendHold(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtendHold", reflect.TypeOf((*MockQuerier)(nil).ExtendHold), ctx, arg)
}

// FailOrder mocks base method.
func (m *MockQuerier) FailOrder(ctx context.Context, arg db.FailOrderParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailOrder", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// FailOrder indicates an expected call of FailOrder.
func (mr *MockQuerierMockRecorder) FailOrder(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailOrder", reflect.TypeOf((*MockQuerier)(nil).FailOrder), ctx, arg)
}

// FindCapturedPaymentsMissingOrderOrRefund mocks base method.
func (m *MockQuerier) FindCapturedPaymentsMissingOrderOrRefund(ctx context.Context) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCapturedPaymentsMissingOrderOrRefund", ctx)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCapturedPaymentsMissingOrderOrRefund indicates an expected call of FindCapturedPaymentsMissingOrderOrRefund.
func (mr *MockQuerierMockRecorder) FindCapturedPaymentsMissingOrderOrRefund(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCapturedPaymentsMissingOrderOrRefund", reflect.TypeOf((*MockQuerier)(nil).FindCapturedPaymentsMissingOrderOrRefund), ctx)
}

// FindOrdersMissingPayment mocks base method.
func (m *MockQuerier) FindOrdersMissingPayment(ctx context.Context) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrdersMissingPayment", ctx)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrdersMissingPayment indicates an expected call of FindOrdersMissingPayment.
func (mr *MockQuerierMockRecorder) FindOrdersMissingPayment(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrdersMissingPayment", reflect.TypeOf((*MockQuerier)(nil).FindOrdersMissingPayment), ctx)
}

// GetEvent mocks base method.
func (m *MockQuerier) GetEvent(ctx context.Context, eventID int64) (db.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvent", ctx, eventID)
	ret0, _ := ret[0].(db.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvent indicates an expected call of GetEvent.
func (mr *MockQuerierMockRecorder) GetEvent(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvent", reflect.TypeOf((*MockQuerier)(nil).GetEvent), ctx, eventID)
}

// GetOrder mocks base method.
func (m *MockQuerier) GetOrder(ctx context.Context, orderID uuid.UUID) (db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", ctx, orderID)
	ret0, _ := ret[0].(db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockQuerierMockRecorder) GetOrder(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockQuerier)(nil).GetOrder), ctx, orderID)
}

// GetOrderByHoldID mocks base method.
func (m *MockQuerier) GetOrderByHoldID(ctx context.Context, holdID uuid.UUID) (db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByHoldID", ctx, holdID)
	ret0, _ := ret[0].(db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByHoldID indicates an expected call of GetOrderByHoldID.
func (mr *MockQuerierMockRecorder) GetOrderByHoldID(ctx, holdID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByHoldID", reflect.TypeOf((*MockQuerier)(nil).GetOrderByHoldID), ctx, holdID)
}

// GetPaymentByIdempotencyKey mocks base method.
func (m *MockQuerier) GetPaymentByIdempotencyKey(ctx context.Context, idempotencyKey string) (db.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentByIdempotencyKey", ctx, idempotencyKey)
	ret0, _ := ret[0].(db.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentByIdempotencyKey indicates an expected call of GetPaymentByIdempotencyKey.
func (mr *MockQuerierMockRecorder) GetPaymentByIdempotencyKey(ctx, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentByIdempotencyKey", reflect.TypeOf((*MockQuerier)(nil).GetPaymentByIdempotencyKey), ctx, idempotencyKey)
}

// GetSagaStep mocks base method.
func (m *MockQuerier) GetSagaStep(ctx context.Context, arg db.GetSagaStepParams) (db.OrderSagaStep, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSagaStep", ctx, arg)
	ret0, _ := ret[0].(db.OrderSagaStep)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSagaStep indicates an expected call of GetSagaStep.
func (mr *MockQuerierMockRecorder) GetSagaStep(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSagaStep", reflect.TypeOf((*MockQuerier)(nil).GetSagaStep), ctx, arg)
}

// GetSeatIDsByOrdinals mocks base method.
func (m *MockQuerier) GetSeatIDsByOrdinals(ctx context.Context, arg db.GetSeatIDsByOrdinalsParams) ([]db.GetSeatIDsByOrdinalsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeatIDsByOrdinals", ctx, arg)
	ret0, _ := ret[0].([]db.GetSeatIDsByOrdinalsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeatIDsByOrdinals indicates an expected call of GetSeatIDsByOrdinals.
func (mr *MockQuerierMockRecorder) GetSeatIDsByOrdinals(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeatIDsByOrdinals", reflect.TypeOf((*MockQuerier)(nil).GetSeatIDsByOrdinals), ctx, arg)
}

// GetSeatsByHoldID mocks base method.
func (m *MockQuerier) GetSeatsByHoldID(ctx context.Context, holdID pgtype.UUID) ([]db.GetSeatsByHoldIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeatsByHoldID", ctx, holdID)
	ret0, _ := ret[0].([]db.GetSeatsByHoldIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeatsByHoldID indicates an expected call of GetSeatsByHoldID.
func (mr *MockQuerierMockRecorder) GetSeatsByHoldID(ctx, holdID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeatsByHoldID", reflect.TypeOf((*MockQuerier)(nil).GetSeatsByHoldID), ctx, holdID)
}

// GetVenue mocks base method.
func (m *MockQuerier) GetVenue(ctx context.Context, venueID int64) (db.Venue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVenue", ctx, venueID)
	ret0, _ := ret[0].(db.Venue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVenue indicates an expected call of GetVenue.
func (mr *MockQuerierMockRecorder) GetVenue(ctx, venueID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVenue", reflect.TypeOf((*MockQuerier)(nil).GetVenue), ctx, venueID)
}

// InsertDomainEvent mocks base method.
func (m *MockQuerier) InsertDomainEvent(ctx context.Context, arg db.InsertDomainEventParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertDomainEvent", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertDomainEvent indicates an expected call of InsertDomainEvent.
func (mr *MockQuerierMockRecorder) InsertDomainEvent(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertDomainEvent", reflect.TypeOf((*MockQuerier)(nil).InsertDomainEvent), ctx, arg)
}

// InsertHoldsAudit mocks base method.
func (m *MockQuerier) InsertHoldsAudit(ctx context.Context, arg db.InsertHoldsAuditParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertHoldsAudit", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertHoldsAudit indicates an expected call of InsertHoldsAudit.
func (mr *MockQuerierMockRecorder) InsertHoldsAudit(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertHoldsAudit", reflect.TypeOf((*MockQuerier)(nil).InsertHoldsAudit), ctx, arg)
}

// InsertPayment mocks base method.
func (m *MockQuerier) InsertPayment(ctx context.Context, arg db.InsertPaymentParams) (db.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPayment", ctx, arg)
	ret0, _ := ret[0].(db.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertPayment indicates an expected call of InsertPayment.
func (mr *MockQuerierMockRecorder) InsertPayment(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPayment", reflect.TypeOf((*MockQuerier)(nil).InsertPayment), ctx, arg)
}

// InsertRefund mocks base method.
func (m *MockQuerier) InsertRefund(ctx context.Context, arg db.InsertRefundParams) (db.Refund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRefund", ctx, arg)
	ret0, _ := ret[0].(db.Refund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertRefund indicates an expected call of InsertRefund.
func (mr *MockQuerierMockRecorder) InsertRefund(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRefund", reflect.TypeOf((*MockQuerier)(nil).InsertRefund), ctx, arg)
}

// InsertWSConnection mocks base method.
func (m *MockQuerier) InsertWSConnection(ctx context.Context, arg db.InsertWSConnectionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertWSConnection", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertWSConnection indicates an expected call of InsertWSConnection.
func (mr *MockQuerierMockRecorder) InsertWSConnection(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertWSConnection", reflect.TypeOf((*MockQuerier)(nil).InsertWSConnection), ctx, arg)
}

// InsertWaitingRoomAudit mocks base method.
func (m *MockQuerier) InsertWaitingRoomAudit(ctx context.Context, arg db.InsertWaitingRoomAuditParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertWaitingRoomAudit", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertWaitingRoomAudit indicates an expected call of InsertWaitingRoomAudit.
func (mr *MockQuerierMockRecorder) InsertWaitingRoomAudit(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertWaitingRoomAudit", reflect.TypeOf((*MockQuerier)(nil).InsertWaitingRoomAudit), ctx, arg)
}

// ListAllEventIDs mocks base method.
func (m *MockQuerier) ListAllEventIDs(ctx context.Context) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllEventIDs", ctx)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllEventIDs indicates an expected call of ListAllEventIDs.
func (mr *MockQuerierMockRecorder) ListAllEventIDs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllEventIDs", reflect.TypeOf((*MockQuerier)(nil).ListAllEventIDs), ctx)
}

// ListAvailableForBestAvailable mocks base method.
func (m *MockQuerier) ListAvailableForBestAvailable(ctx context.Context, arg db.ListAvailableForBestAvailableParams) ([]db.ListAvailableForBestAvailableRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAvailableForBestAvailable", ctx, arg)
	ret0, _ := ret[0].([]db.ListAvailableForBestAvailableRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAvailableForBestAvailable indicates an expected call of ListAvailableForBestAvailable.
func (mr *MockQuerierMockRecorder) ListAvailableForBestAvailable(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAvailableForBestAvailable", reflect.TypeOf((*MockQuerier)(nil).ListAvailableForBestAvailable), ctx, arg)
}

// ListClosedSectionsForEvent mocks base method.
func (m *MockQuerier) ListClosedSectionsForEvent(ctx context.Context, eventID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClosedSectionsForEvent", ctx, eventID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClosedSectionsForEvent indicates an expected call of ListClosedSectionsForEvent.
func (mr *MockQuerierMockRecorder) ListClosedSectionsForEvent(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClosedSectionsForEvent", reflect.TypeOf((*MockQuerier)(nil).ListClosedSectionsForEvent), ctx, eventID)
}

// ListEventPriceTiers mocks base method.
func (m *MockQuerier) ListEventPriceTiers(ctx context.Context, eventID int64) ([]db.EventPriceTier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEventPriceTiers", ctx, eventID)
	ret0, _ := ret[0].([]db.EventPriceTier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEventPriceTiers indicates an expected call of ListEventPriceTiers.
func (mr *MockQuerierMockRecorder) ListEventPriceTiers(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEventPriceTiers", reflect.TypeOf((*MockQuerier)(nil).ListEventPriceTiers), ctx, eventID)
}

// ListEventSeatsForAvailability mocks base method.
func (m *MockQuerier) ListEventSeatsForAvailability(ctx context.Context, eventID int64) ([]db.ListEventSeatsForAvailabilityRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEventSeatsForAvailability", ctx, eventID)
	ret0, _ := ret[0].([]db.ListEventSeatsForAvailabilityRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEventSeatsForAvailability indicates an expected call of ListEventSeatsForAvailability.
func (mr *MockQuerierMockRecorder) ListEventSeatsForAvailability(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEventSeatsForAvailability", reflect.TypeOf((*MockQuerier)(nil).ListEventSeatsForAvailability), ctx, eventID)
}

// ListEvents mocks base method.
func (m *MockQuerier) ListEvents(ctx context.Context, arg db.ListEventsParams) ([]db.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", ctx, arg)
	ret0, _ := ret[0].([]db.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockQuerierMockRecorder) ListEvents(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockQuerier)(nil).ListEvents), ctx, arg)
}

// ListExpiredHolds mocks base method.
func (m *MockQuerier) ListExpiredHolds(ctx context.Context) ([]db.ListExpiredHoldsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExpiredHolds", ctx)
	ret0, _ := ret[0].([]db.ListExpiredHoldsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExpiredHolds indicates an expected call of ListExpiredHolds.
func (mr *MockQuerierMockRecorder) ListExpiredHolds(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExpiredHolds", reflect.TypeOf((*MockQuerier)(nil).ListExpiredHolds), ctx)
}

// ListSeatIDsForHold mocks base method.
func (m *MockQuerier) ListSeatIDsForHold(ctx context.Context, arg db.ListSeatIDsForHoldParams) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSeatIDsForHold", ctx, arg)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSeatIDsForHold indicates an expected call of ListSeatIDsForHold.
func (mr *MockQuerierMockRecorder) ListSeatIDsForHold(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSeatIDsForHold", reflect.TypeOf((*MockQuerier)(nil).ListSeatIDsForHold), ctx, arg)
}

// ListSeatOrdinalsByEvent mocks base method.
func (m *MockQuerier) ListSeatOrdinalsByEvent(ctx context.Context, eventID int64) ([]db.ListSeatOrdinalsByEventRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSeatOrdinalsByEvent", ctx, eventID)
	ret0, _ := ret[0].([]db.ListSeatOrdinalsByEventRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSeatOrdinalsByEvent indicates an expected call of ListSeatOrdinalsByEvent.
func (mr *MockQuerierMockRecorder) ListSeatOrdinalsByEvent(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSeatOrdinalsByEvent", reflect.TypeOf((*MockQuerier)(nil).ListSeatOrdinalsByEvent), ctx, eventID)
}

// ListStuckOrders mocks base method.
func (m *MockQuerier) ListStuckOrders(ctx context.Context, arg db.ListStuckOrdersParams) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStuckOrders", ctx, arg)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStuckOrders indicates an expected call of ListStuckOrders.
func (mr *MockQuerierMockRecorder) ListStuckOrders(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStuckOrders", reflect.TypeOf((*MockQuerier)(nil).ListStuckOrders), ctx, arg)
}

// ListStuckPayments mocks base method.
func (m *MockQuerier) ListStuckPayments(ctx context.Context, arg db.ListStuckPaymentsParams) ([]db.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStuckPayments", ctx, arg)
	ret0, _ := ret[0].([]db.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStuckPayments indicates an expected call of ListStuckPayments.
func (mr *MockQuerierMockRecorder) ListStuckPayments(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStuckPayments", reflect.TypeOf((*MockQuerier)(nil).ListStuckPayments), ctx, arg)
}

// ListUnprocessedDomainEvents mocks base method.
func (m *MockQuerier) ListUnprocessedDomainEvents(ctx context.Context, arg db.ListUnprocessedDomainEventsParams) ([]db.ListUnprocessedDomainEventsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnprocessedDomainEvents", ctx, arg)
	ret0, _ := ret[0].([]db.ListUnprocessedDomainEventsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnprocessedDomainEvents indicates an expected call of ListUnprocessedDomainEvents.
func (mr *MockQuerierMockRecorder) ListUnprocessedDomainEvents(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnprocessedDomainEvents", reflect.TypeOf((*MockQuerier)(nil).ListUnprocessedDomainEvents), ctx, arg)
}

// ListUnpublishedDomainEvents mocks base method.
func (m *MockQuerier) ListUnpublishedDomainEvents(ctx context.Context, rowLimit int32) ([]db.ListUnpublishedDomainEventsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnpublishedDomainEvents", ctx, rowLimit)
	ret0, _ := ret[0].([]db.ListUnpublishedDomainEventsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnpublishedDomainEvents indicates an expected call of ListUnpublishedDomainEvents.
func (mr *MockQuerierMockRecorder) ListUnpublishedDomainEvents(ctx, rowLimit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnpublishedDomainEvents", reflect.TypeOf((*MockQuerier)(nil).ListUnpublishedDomainEvents), ctx, rowLimit)
}

// ListVenueSeatsOrdered mocks base method.
func (m *MockQuerier) ListVenueSeatsOrdered(ctx context.Context, venueID int64) ([]db.ListVenueSeatsOrderedRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVenueSeatsOrdered", ctx, venueID)
	ret0, _ := ret[0].([]db.ListVenueSeatsOrderedRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVenueSeatsOrdered indicates an expected call of ListVenueSeatsOrdered.
func (mr *MockQuerierMockRecorder) ListVenueSeatsOrdered(ctx, venueID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVenueSeatsOrdered", reflect.TypeOf((*MockQuerier)(nil).ListVenueSeatsOrdered), ctx, venueID)
}

// ListWaitingRoomAudit mocks base method.
func (m *MockQuerier) ListWaitingRoomAudit(ctx context.Context, eventID int64) ([]db.WaitingRoomAudit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWaitingRoomAudit", ctx, eventID)
	ret0, _ := ret[0].([]db.WaitingRoomAudit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWaitingRoomAudit indicates an expected call of ListWaitingRoomAudit.
func (mr *MockQuerierMockRecorder) ListWaitingRoomAudit(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWaitingRoomAudit", reflect.TypeOf((*MockQuerier)(nil).ListWaitingRoomAudit), ctx, eventID)
}

// MarkDomainEventPublished mocks base method.
func (m *MockQuerier) MarkDomainEventPublished(ctx context.Context, eventID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkDomainEventPublished", ctx, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkDomainEventPublished indicates an expected call of MarkDomainEventPublished.
func (mr *MockQuerierMockRecorder) MarkDomainEventPublished(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkDomainEventPublished", reflect.TypeOf((*MockQuerier)(nil).MarkDomainEventPublished), ctx, eventID)
}

// MarkEventProcessed mocks base method.
func (m *MockQuerier) MarkEventProcessed(ctx context.Context, arg db.MarkEventProcessedParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkEventProcessed", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkEventProcessed indicates an expected call of MarkEventProcessed.
func (mr *MockQuerierMockRecorder) MarkEventProcessed(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkEventProcessed", reflect.TypeOf((*MockQuerier)(nil).MarkEventProcessed), ctx, arg)
}

// MinEventPriceCents mocks base method.
func (m *MockQuerier) MinEventPriceCents(ctx context.Context, eventID int64) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MinEventPriceCents", ctx, eventID)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MinEventPriceCents indicates an expected call of MinEventPriceCents.
func (mr *MockQuerierMockRecorder) MinEventPriceCents(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MinEventPriceCents", reflect.TypeOf((*MockQuerier)(nil).MinEventPriceCents), ctx, eventID)
}

// ReallocateOrder mocks base method.
func (m *MockQuerier) ReallocateOrder(ctx context.Context, arg db.ReallocateOrderParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReallocateOrder", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReallocateOrder indicates an expected call of ReallocateOrder.
func (mr *MockQuerierMockRecorder) ReallocateOrder(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReallocateOrder", reflect.TypeOf((*MockQuerier)(nil).ReallocateOrder), ctx, arg)
}

// ReleaseHold mocks base method.
func (m *MockQuerier) ReleaseHold(ctx context.Context, arg db.ReleaseHoldParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseHold", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseHold indicates an expected call of ReleaseHold.
func (mr *MockQuerierMockRecorder) ReleaseHold(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseHold", reflect.TypeOf((*MockQuerier)(nil).ReleaseHold), ctx, arg)
}

// SetEventOnSale mocks base method.
func (m *MockQuerier) SetEventOnSale(ctx context.Context, eventID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEventOnSale", ctx, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEventOnSale indicates an expected call of SetEventOnSale.
func (mr *MockQuerierMockRecorder) SetEventOnSale(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEventOnSale", reflect.TypeOf((*MockQuerier)(nil).SetEventOnSale), ctx, eventID)
}

// UpdateOrderStatus mocks base method.
func (m *MockQuerier) UpdateOrderStatus(ctx context.Context, arg db.UpdateOrderStatusParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockQuerierMockRecorder) UpdateOrderStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockQuerier)(nil).UpdateOrderStatus), ctx, arg)
}

// UpdatePaymentStatus mocks base method.
func (m *MockQuerier) UpdatePaymentStatus(ctx context.Context, arg db.UpdatePaymentStatusParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePaymentStatus", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePaymentStatus indicates an expected call of UpdatePaymentStatus.
func (mr *MockQuerierMockRecorder) UpdatePaymentStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePaymentStatus", reflect.TypeOf((*MockQuerier)(nil).UpdatePaymentStatus), ctx, arg)
}

// UpdateSagaStep mocks base method.
func (m *MockQuerier) UpdateSagaStep(ctx context.Context, arg db.UpdateSagaStepParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSagaStep", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSagaStep indicates an expected call of UpdateSagaStep.
func (mr *MockQuerierMockRecorder) UpdateSagaStep(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSagaStep", reflect.TypeOf((*MockQuerier)(nil).UpdateSagaStep), ctx, arg)
}

// UpdateWSConnectionSeq mocks base method.
func (m *MockQuerier) UpdateWSConnectionSeq(ctx context.Context, arg db.UpdateWSConnectionSeqParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWSConnectionSeq", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWSConnectionSeq indicates an expected call of UpdateWSConnectionSeq.
func (mr *MockQuerierMockRecorder) UpdateWSConnectionSeq(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWSConnectionSeq", reflect.TypeOf((*MockQuerier)(nil).UpdateWSConnectionSeq), ctx, arg)
}
