// Code generated by MockGen. DO NOT EDIT.
// Source: internal/db/querier.go
//
// Generated by this command:
//
//	mockgen -source=internal/db/querier.go -destination=internal/inventory/mocks/querier_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	db "ticketing/internal/db"

	uuid "github.com/google/uuid"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// AcquireHold mocks base method.
func (m *MockQuerier) AcquireHold(ctx context.Context, arg db.AcquireHoldParams) ([]db.AcquireHoldRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireHold", ctx, arg)
	ret0, _ := ret[0].([]db.AcquireHoldRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcquireHold indicates an expected call of AcquireHold.
func (mr *MockQuerierMockRecorder) AcquireHold(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireHold", reflect.TypeOf((*MockQuerier)(nil).AcquireHold), ctx, arg)
}

// BulkInsertEventSeats mocks base method.
func (m *MockQuerier) BulkInsertEventSeats(ctx context.Context, arg []db.BulkInsertEventSeatsParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkInsertEventSeats", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkInsertEventSeats indicates an expected call of BulkInsertEventSeats.
func (mr *MockQuerierMockRecorder) BulkInsertEventSeats(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkInsertEventSeats", reflect.TypeOf((*MockQuerier)(nil).BulkInsertEventSeats), ctx, arg)
}

// ConfirmSeats mocks base method.
func (m *MockQuerier) ConfirmSeats(ctx context.Context, arg db.ConfirmSeatsParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmSeats", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmSeats indicates an expected call of ConfirmSeats.
func (mr *MockQuerierMockRecorder) ConfirmSeats(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmSeats", reflect.TypeOf((*MockQuerier)(nil).ConfirmSeats), ctx, arg)
}

// CountAvailableSeats mocks base method.
func (m *MockQuerier) CountAvailableSeats(ctx context.Context, eventID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAvailableSeats", ctx, eventID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAvailableSeats indicates an expected call of CountAvailableSeats.
func (mr *MockQuerierMockRecorder) CountAvailableSeats(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAvailableSeats", reflect.TypeOf((*MockQuerier)(nil).CountAvailableSeats), ctx, eventID)
}

// CountEventSeats mocks base method.
func (m *MockQuerier) CountEventSeats(ctx context.Context, eventID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountEventSeats", ctx, eventID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountEventSeats indicates an expected call of CountEventSeats.
func (mr *MockQuerierMockRecorder) CountEventSeats(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountEventSeats", reflect.TypeOf((*MockQuerier)(nil).CountEventSeats), ctx, eventID)
}

// CreateEvent mocks base method.
func (m *MockQuerier) CreateEvent(ctx context.Context, arg db.CreateEventParams) (db.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvent", ctx, arg)
	ret0, _ := ret[0].(db.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEvent indicates an expected call of CreateEvent.
func (mr *MockQuerierMockRecorder) CreateEvent(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvent", reflect.TypeOf((*MockQuerier)(nil).CreateEvent), ctx, arg)
}

// CreateEventPriceTier mocks base method.
func (m *MockQuerier) CreateEventPriceTier(ctx context.Context, arg db.CreateEventPriceTierParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEventPriceTier", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEventPriceTier indicates an expected call of CreateEventPriceTier.
func (mr *MockQuerierMockRecorder) CreateEventPriceTier(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEventPriceTier", reflect.TypeOf((*MockQuerier)(nil).CreateEventPriceTier), ctx, arg)
}

// CreateSeat mocks base method.
func (m *MockQuerier) CreateSeat(ctx context.Context, arg db.CreateSeatParams) (db.Seat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSeat", ctx, arg)
	ret0, _ := ret[0].(db.Seat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSeat indicates an expected call of CreateSeat.
func (mr *MockQuerierMockRecorder) CreateSeat(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSeat", reflect.TypeOf((*MockQuerier)(nil).CreateSeat), ctx, arg)
}

// CreateSeatRow mocks base method.
func (m *MockQuerier) CreateSeatRow(ctx context.Context, arg db.CreateSeatRowParams) (db.SeatRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSeatRow", ctx, arg)
	ret0, _ := ret[0].(db.SeatRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSeatRow indicates an expected call of CreateSeatRow.
func (mr *MockQuerierMockRecorder) CreateSeatRow(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSeatRow", reflect.TypeOf((*MockQuerier)(nil).CreateSeatRow), ctx, arg)
}

// CreateSection mocks base method.
func (m *MockQuerier) CreateSection(ctx context.Context, arg db.CreateSectionParams) (db.Section, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSection", ctx, arg)
	ret0, _ := ret[0].(db.Section)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSection indicates an expected call of CreateSection.
func (mr *MockQuerierMockRecorder) CreateSection(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSection", reflect.TypeOf((*MockQuerier)(nil).CreateSection), ctx, arg)
}

// CreateVenue mocks base method.
func (m *MockQuerier) CreateVenue(ctx context.Context, arg db.CreateVenueParams) (db.Venue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVenue", ctx, arg)
	ret0, _ := ret[0].(db.Venue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVenue indicates an expected call of CreateVenue.
func (mr *MockQuerierMockRecorder) CreateVenue(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVenue", reflect.TypeOf((*MockQuerier)(nil).CreateVenue), ctx, arg)
}

// ExtendHold mocks base method.
func (m *MockQuerier) ExtendHold(ctx context.Context, arg db.ExtendHoldParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtendHold", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtendHold indicates an expected call of ExtendHold.
func (mr *MockQuerierMockRecorder) ExtendHold(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtendHold", reflect.TypeOf((*MockQuerier)(nil).ExtendHold), ctx, arg)
}

// GetEvent mocks base method.
func (m *MockQuerier) GetEvent(ctx context.Context, eventID int64) (db.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvent", ctx, eventID)
	ret0, _ := ret[0].(db.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvent indicates an expected call of GetEvent.
func (mr *MockQuerierMockRecorder) GetEvent(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvent", reflect.TypeOf((*MockQuerier)(nil).GetEvent), ctx, eventID)
}

// GetSeatIDsByOrdinals mocks base method.
func (m *MockQuerier) GetSeatIDsByOrdinals(ctx context.Context, arg db.GetSeatIDsByOrdinalsParams) ([]db.GetSeatIDsByOrdinalsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeatIDsByOrdinals", ctx, arg)
	ret0, _ := ret[0].([]db.GetSeatIDsByOrdinalsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeatIDsByOrdinals indicates an expected call of GetSeatIDsByOrdinals.
func (mr *MockQuerierMockRecorder) GetSeatIDsByOrdinals(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeatIDsByOrdinals", reflect.TypeOf((*MockQuerier)(nil).GetSeatIDsByOrdinals), ctx, arg)
}

// GetSeatsByHoldID mocks base method.
func (m *MockQuerier) GetSeatsByHoldID(ctx context.Context, holdID pgtype.UUID) ([]db.GetSeatsByHoldIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeatsByHoldID", ctx, holdID)
	ret0, _ := ret[0].([]db.GetSeatsByHoldIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeatsByHoldID indicates an expected call of GetSeatsByHoldID.
func (mr *MockQuerierMockRecorder) GetSeatsByHoldID(ctx, holdID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeatsByHoldID", reflect.TypeOf((*MockQuerier)(nil).GetSeatsByHoldID), ctx, holdID)
}

// GetVenue mocks base method.
func (m *MockQuerier) GetVenue(ctx context.Context, venueID int64) (db.Venue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVenue", ctx, venueID)
	ret0, _ := ret[0].(db.Venue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVenue indicates an expected call of GetVenue.
func (mr *MockQuerierMockRecorder) GetVenue(ctx, venueID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVenue", reflect.TypeOf((*MockQuerier)(nil).GetVenue), ctx, venueID)
}

// InsertDomainEvent mocks base method.
func (m *MockQuerier) InsertDomainEvent(ctx context.Context, arg db.InsertDomainEventParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertDomainEvent", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertDomainEvent indicates an expected call of InsertDomainEvent.
func (mr *MockQuerierMockRecorder) InsertDomainEvent(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertDomainEvent", reflect.TypeOf((*MockQuerier)(nil).InsertDomainEvent), ctx, arg)
}

// InsertHoldsAudit mocks base method.
func (m *MockQuerier) InsertHoldsAudit(ctx context.Context, arg db.InsertHoldsAuditParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertHoldsAudit", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertHoldsAudit indicates an expected call of InsertHoldsAudit.
func (mr *MockQuerierMockRecorder) InsertHoldsAudit(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertHoldsAudit", reflect.TypeOf((*MockQuerier)(nil).InsertHoldsAudit), ctx, arg)
}

// ListAvailableForBestAvailable mocks base method.
func (m *MockQuerier) ListAvailableForBestAvailable(ctx context.Context, arg db.ListAvailableForBestAvailableParams) ([]db.ListAvailableForBestAvailableRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAvailableForBestAvailable", ctx, arg)
	ret0, _ := ret[0].([]db.ListAvailableForBestAvailableRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAvailableForBestAvailable indicates an expected call of ListAvailableForBestAvailable.
func (mr *MockQuerierMockRecorder) ListAvailableForBestAvailable(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAvailableForBestAvailable", reflect.TypeOf((*MockQuerier)(nil).ListAvailableForBestAvailable), ctx, arg)
}

// ListClosedSectionsForEvent mocks base method.
func (m *MockQuerier) ListClosedSectionsForEvent(ctx context.Context, eventID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClosedSectionsForEvent", ctx, eventID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClosedSectionsForEvent indicates an expected call of ListClosedSectionsForEvent.
func (mr *MockQuerierMockRecorder) ListClosedSectionsForEvent(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClosedSectionsForEvent", reflect.TypeOf((*MockQuerier)(nil).ListClosedSectionsForEvent), ctx, eventID)
}

// ListEventPriceTiers mocks base method.
func (m *MockQuerier) ListEventPriceTiers(ctx context.Context, eventID int64) ([]db.EventPriceTier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEventPriceTiers", ctx, eventID)
	ret0, _ := ret[0].([]db.EventPriceTier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEventPriceTiers indicates an expected call of ListEventPriceTiers.
func (mr *MockQuerierMockRecorder) ListEventPriceTiers(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEventPriceTiers", reflect.TypeOf((*MockQuerier)(nil).ListEventPriceTiers), ctx, eventID)
}

// ListEventSeatsForAvailability mocks base method.
func (m *MockQuerier) ListEventSeatsForAvailability(ctx context.Context, eventID int64) ([]db.ListEventSeatsForAvailabilityRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEventSeatsForAvailability", ctx, eventID)
	ret0, _ := ret[0].([]db.ListEventSeatsForAvailabilityRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEventSeatsForAvailability indicates an expected call of ListEventSeatsForAvailability.
func (mr *MockQuerierMockRecorder) ListEventSeatsForAvailability(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEventSeatsForAvailability", reflect.TypeOf((*MockQuerier)(nil).ListEventSeatsForAvailability), ctx, eventID)
}

// ListEvents mocks base method.
func (m *MockQuerier) ListEvents(ctx context.Context, arg db.ListEventsParams) ([]db.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", ctx, arg)
	ret0, _ := ret[0].([]db.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockQuerierMockRecorder) ListEvents(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockQuerier)(nil).ListEvents), ctx, arg)
}

// ListExpiredHolds mocks base method.
func (m *MockQuerier) ListExpiredHolds(ctx context.Context) ([]db.ListExpiredHoldsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExpiredHolds", ctx)
	ret0, _ := ret[0].([]db.ListExpiredHoldsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExpiredHolds indicates an expected call of ListExpiredHolds.
func (mr *MockQuerierMockRecorder) ListExpiredHolds(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExpiredHolds", reflect.TypeOf((*MockQuerier)(nil).ListExpiredHolds), ctx)
}

// ListSeatIDsForHold mocks base method.
func (m *MockQuerier) ListSeatIDsForHold(ctx context.Context, arg db.ListSeatIDsForHoldParams) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSeatIDsForHold", ctx, arg)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSeatIDsForHold indicates an expected call of ListSeatIDsForHold.
func (mr *MockQuerierMockRecorder) ListSeatIDsForHold(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSeatIDsForHold", reflect.TypeOf((*MockQuerier)(nil).ListSeatIDsForHold), ctx, arg)
}

// ListUnpublishedDomainEvents mocks base method.
func (m *MockQuerier) ListUnpublishedDomainEvents(ctx context.Context, rowLimit int32) ([]db.ListUnpublishedDomainEventsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnpublishedDomainEvents", ctx, rowLimit)
	ret0, _ := ret[0].([]db.ListUnpublishedDomainEventsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnpublishedDomainEvents indicates an expected call of ListUnpublishedDomainEvents.
func (mr *MockQuerierMockRecorder) ListUnpublishedDomainEvents(ctx, rowLimit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnpublishedDomainEvents", reflect.TypeOf((*MockQuerier)(nil).ListUnpublishedDomainEvents), ctx, rowLimit)
}

// ListVenueSeatsOrdered mocks base method.
func (m *MockQuerier) ListVenueSeatsOrdered(ctx context.Context, venueID int64) ([]db.ListVenueSeatsOrderedRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVenueSeatsOrdered", ctx, venueID)
	ret0, _ := ret[0].([]db.ListVenueSeatsOrderedRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVenueSeatsOrdered indicates an expected call of ListVenueSeatsOrdered.
func (mr *MockQuerierMockRecorder) ListVenueSeatsOrdered(ctx, venueID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVenueSeatsOrdered", reflect.TypeOf((*MockQuerier)(nil).ListVenueSeatsOrdered), ctx, venueID)
}

// MarkDomainEventPublished mocks base method.
func (m *MockQuerier) MarkDomainEventPublished(ctx context.Context, eventID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkDomainEventPublished", ctx, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkDomainEventPublished indicates an expected call of MarkDomainEventPublished.
func (mr *MockQuerierMockRecorder) MarkDomainEventPublished(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkDomainEventPublished", reflect.TypeOf((*MockQuerier)(nil).MarkDomainEventPublished), ctx, eventID)
}

// MinEventPriceCents mocks base method.
func (m *MockQuerier) MinEventPriceCents(ctx context.Context, eventID int64) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MinEventPriceCents", ctx, eventID)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MinEventPriceCents indicates an expected call of MinEventPriceCents.
func (mr *MockQuerierMockRecorder) MinEventPriceCents(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MinEventPriceCents", reflect.TypeOf((*MockQuerier)(nil).MinEventPriceCents), ctx, eventID)
}

// ReleaseHold mocks base method.
func (m *MockQuerier) ReleaseHold(ctx context.Context, arg db.ReleaseHoldParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseHold", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseHold indicates an expected call of ReleaseHold.
func (mr *MockQuerierMockRecorder) ReleaseHold(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseHold", reflect.TypeOf((*MockQuerier)(nil).ReleaseHold), ctx, arg)
}

// SetEventOnSale mocks base method.
func (m *MockQuerier) SetEventOnSale(ctx context.Context, eventID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEventOnSale", ctx, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEventOnSale indicates an expected call of SetEventOnSale.
func (mr *MockQuerierMockRecorder) SetEventOnSale(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEventOnSale", reflect.TypeOf((*MockQuerier)(nil).SetEventOnSale), ctx, eventID)
}
