#!/usr/bin/env bash
# Seeds a User Pool + App Client in cognito-local (idempotent) and writes the
# resulting IDs to .env.local for the web app / backend to pick up.
#
# cognito-local doesn't implement SRP (jagregory/cognito-local issue #348
# discussion + general known limitation), so the app client is created with
# ALLOW_USER_PASSWORD_AUTH — the frontend must request USER_PASSWORD_AUTH,
# not the SRP flow Amplify defaults to against real Cognito.
set -euo pipefail

export AWS_ACCESS_KEY_ID=local
export AWS_SECRET_ACCESS_KEY=local
export AWS_DEFAULT_REGION=us-east-1
ENDPOINT="http://localhost:9229"
POOL_NAME="ticketing-local"
CLIENT_NAME="ticketing-web"
ENV_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/.env.local"

aws_local() { aws --endpoint-url "$ENDPOINT" "$@"; }

EXISTING_POOL_ID=$(aws_local cognito-idp list-user-pools --max-results 60 \
  --query "UserPools[?Name=='${POOL_NAME}'].Id | [0]" --output text)

if [[ "$EXISTING_POOL_ID" != "None" && -n "$EXISTING_POOL_ID" ]]; then
  POOL_ID="$EXISTING_POOL_ID"
  echo "Reusing existing user pool: $POOL_ID"
else
  POOL_ID=$(aws_local cognito-idp create-user-pool --pool-name "$POOL_NAME" \
    --query 'UserPool.Id' --output text)
  echo "Created user pool: $POOL_ID"
fi

EXISTING_CLIENT_ID=$(aws_local cognito-idp list-user-pool-clients --user-pool-id "$POOL_ID" \
  --query "UserPoolClients[?ClientName=='${CLIENT_NAME}'].ClientId | [0]" --output text)

if [[ "$EXISTING_CLIENT_ID" != "None" && -n "$EXISTING_CLIENT_ID" ]]; then
  CLIENT_ID="$EXISTING_CLIENT_ID"
  echo "Reusing existing app client: $CLIENT_ID"
else
  CLIENT_ID=$(aws_local cognito-idp create-user-pool-client \
    --user-pool-id "$POOL_ID" \
    --client-name "$CLIENT_NAME" \
    --no-generate-secret \
    --explicit-auth-flows ALLOW_USER_PASSWORD_AUTH ALLOW_REFRESH_TOKEN_AUTH \
    --query 'UserPoolClient.ClientId' --output text)
  echo "Created app client: $CLIENT_ID"
fi

cat > "$ENV_FILE" <<EOF
# generated by scripts/seed-cognito-local.sh — do not edit by hand
VITE_COGNITO_ENDPOINT=${ENDPOINT}
VITE_COGNITO_USER_POOL_ID=${POOL_ID}
VITE_COGNITO_CLIENT_ID=${CLIENT_ID}
VITE_API_URL=http://localhost:8080
COGNITO_ENDPOINT=${ENDPOINT}
COGNITO_USER_POOL_ID=${POOL_ID}
COGNITO_CLIENT_ID=${CLIENT_ID}
EOF

echo "Wrote $ENV_FILE"
