// Code generated by MockGen. DO NOT EDIT.
// Source: internal/db/querier.go
//
// Generated by this command:
//
//	mockgen -source=internal/db/querier.go -destination=internal/sync/mocks/querier_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	db "fieldsync/internal/db"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// CountPhotosByConditionForLocation mocks base method.
func (m *MockQuerier) CountPhotosByConditionForLocation(ctx context.Context, locationID uuid.UUID) ([]db.CountPhotosByConditionForLocationRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPhotosByConditionForLocation", ctx, locationID)
	ret0, _ := ret[0].([]db.CountPhotosByConditionForLocationRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPhotosByConditionForLocation indicates an expected call of CountPhotosByConditionForLocation.
func (mr *MockQuerierMockRecorder) CountPhotosByConditionForLocation(ctx, locationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPhotosByConditionForLocation", reflect.TypeOf((*MockQuerier)(nil).CountPhotosByConditionForLocation), ctx, locationID)
}

// CountPhotosBySite mocks base method.
func (m *MockQuerier) CountPhotosBySite(ctx context.Context, siteAssessmentID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPhotosBySite", ctx, siteAssessmentID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPhotosBySite indicates an expected call of CountPhotosBySite.
func (mr *MockQuerierMockRecorder) CountPhotosBySite(ctx, siteAssessmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPhotosBySite", reflect.TypeOf((*MockQuerier)(nil).CountPhotosBySite), ctx, siteAssessmentID)
}

// DeleteWSConnection mocks base method.
func (m *MockQuerier) DeleteWSConnection(ctx context.Context, connectionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWSConnection", ctx, connectionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWSConnection indicates an expected call of DeleteWSConnection.
func (mr *MockQuerierMockRecorder) DeleteWSConnection(ctx, connectionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWSConnection", reflect.TypeOf((*MockQuerier)(nil).DeleteWSConnection), ctx, connectionID)
}

// GetLocation mocks base method.
func (m *MockQuerier) GetLocation(ctx context.Context, id uuid.UUID) (db.DisasterLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocation", ctx, id)
	ret0, _ := ret[0].(db.DisasterLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLocation indicates an expected call of GetLocation.
func (mr *MockQuerierMockRecorder) GetLocation(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocation", reflect.TypeOf((*MockQuerier)(nil).GetLocation), ctx, id)
}

// GetLocationStats mocks base method.
func (m *MockQuerier) GetLocationStats(ctx context.Context, locationID uuid.UUID) (db.LocationStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocationStats", ctx, locationID)
	ret0, _ := ret[0].(db.LocationStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLocationStats indicates an expected call of GetLocationStats.
func (mr *MockQuerierMockRecorder) GetLocationStats(ctx, locationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocationStats", reflect.TypeOf((*MockQuerier)(nil).GetLocationStats), ctx, locationID)
}

// GetPhoto mocks base method.
func (m *MockQuerier) GetPhoto(ctx context.Context, id uuid.UUID) (db.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhoto", ctx, id)
	ret0, _ := ret[0].(db.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPhoto indicates an expected call of GetPhoto.
func (mr *MockQuerierMockRecorder) GetPhoto(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhoto", reflect.TypeOf((*MockQuerier)(nil).GetPhoto), ctx, id)
}

// GetSiteAssessment mocks base method.
func (m *MockQuerier) GetSiteAssessment(ctx context.Context, id uuid.UUID) (db.SiteAssessment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSiteAssessment", ctx, id)
	ret0, _ := ret[0].(db.SiteAssessment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSiteAssessment indicates an expected call of GetSiteAssessment.
func (mr *MockQuerierMockRecorder) GetSiteAssessment(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSiteAssessment", reflect.TypeOf((*MockQuerier)(nil).GetSiteAssessment), ctx, id)
}

// InsertDomainEvent mocks base method.
func (m *MockQuerier) InsertDomainEvent(ctx context.Context, arg db.InsertDomainEventParams) (db.DomainEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertDomainEvent", ctx, arg)
	ret0, _ := ret[0].(db.DomainEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertDomainEvent indicates an expected call of InsertDomainEvent.
func (mr *MockQuerierMockRecorder) InsertDomainEvent(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertDomainEvent", reflect.TypeOf((*MockQuerier)(nil).InsertDomainEvent), ctx, arg)
}

// InsertWSConnection mocks base method.
func (m *MockQuerier) InsertWSConnection(ctx context.Context, arg db.InsertWSConnectionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertWSConnection", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertWSConnection indicates an expected call of InsertWSConnection.
func (mr *MockQuerierMockRecorder) InsertWSConnection(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertWSConnection", reflect.TypeOf((*MockQuerier)(nil).InsertWSConnection), ctx, arg)
}

// IsEventProcessed mocks base method.
func (m *MockQuerier) IsEventProcessed(ctx context.Context, arg db.IsEventProcessedParams) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEventProcessed", ctx, arg)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsEventProcessed indicates an expected call of IsEventProcessed.
func (mr *MockQuerierMockRecorder) IsEventProcessed(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEventProcessed", reflect.TypeOf((*MockQuerier)(nil).IsEventProcessed), ctx, arg)
}

// ListPhotosBySite mocks base method.
func (m *MockQuerier) ListPhotosBySite(ctx context.Context, siteAssessmentID uuid.UUID) ([]db.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPhotosBySite", ctx, siteAssessmentID)
	ret0, _ := ret[0].([]db.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPhotosBySite indicates an expected call of ListPhotosBySite.
func (mr *MockQuerierMockRecorder) ListPhotosBySite(ctx, siteAssessmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPhotosBySite", reflect.TypeOf((*MockQuerier)(nil).ListPhotosBySite), ctx, siteAssessmentID)
}

// ListSiteAssessmentsByLocation mocks base method.
func (m *MockQuerier) ListSiteAssessmentsByLocation(ctx context.Context, locationID uuid.UUID) ([]db.SiteAssessment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSiteAssessmentsByLocation", ctx, locationID)
	ret0, _ := ret[0].([]db.SiteAssessment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSiteAssessmentsByLocation indicates an expected call of ListSiteAssessmentsByLocation.
func (mr *MockQuerierMockRecorder) ListSiteAssessmentsByLocation(ctx, locationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSiteAssessmentsByLocation", reflect.TypeOf((*MockQuerier)(nil).ListSiteAssessmentsByLocation), ctx, locationID)
}

// ListUnprocessedEventsForConsumer mocks base method.
func (m *MockQuerier) ListUnprocessedEventsForConsumer(ctx context.Context, arg db.ListUnprocessedEventsForConsumerParams) ([]db.DomainEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnprocessedEventsForConsumer", ctx, arg)
	ret0, _ := ret[0].([]db.DomainEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnprocessedEventsForConsumer indicates an expected call of ListUnprocessedEventsForConsumer.
func (mr *MockQuerierMockRecorder) ListUnprocessedEventsForConsumer(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnprocessedEventsForConsumer", reflect.TypeOf((*MockQuerier)(nil).ListUnprocessedEventsForConsumer), ctx, arg)
}

// ListUnpublishedEvents mocks base method.
func (m *MockQuerier) ListUnpublishedEvents(ctx context.Context, limit int32) ([]db.DomainEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnpublishedEvents", ctx, limit)
	ret0, _ := ret[0].([]db.DomainEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnpublishedEvents indicates an expected call of ListUnpublishedEvents.
func (mr *MockQuerierMockRecorder) ListUnpublishedEvents(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnpublishedEvents", reflect.TypeOf((*MockQuerier)(nil).ListUnpublishedEvents), ctx, limit)
}

// ListWSConnectionsByLocation mocks base method.
func (m *MockQuerier) ListWSConnectionsByLocation(ctx context.Context, locationID uuid.UUID) ([]db.WsConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWSConnectionsByLocation", ctx, locationID)
	ret0, _ := ret[0].([]db.WsConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWSConnectionsByLocation indicates an expected call of ListWSConnectionsByLocation.
func (mr *MockQuerierMockRecorder) ListWSConnectionsByLocation(ctx, locationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWSConnectionsByLocation", reflect.TypeOf((*MockQuerier)(nil).ListWSConnectionsByLocation), ctx, locationID)
}

// MarkEventProcessed mocks base method.
func (m *MockQuerier) MarkEventProcessed(ctx context.Context, arg db.MarkEventProcessedParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkEventProcessed", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkEventProcessed indicates an expected call of MarkEventProcessed.
func (mr *MockQuerierMockRecorder) MarkEventProcessed(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkEventProcessed", reflect.TypeOf((*MockQuerier)(nil).MarkEventProcessed), ctx, arg)
}

// MarkEventPublished mocks base method.
func (m *MockQuerier) MarkEventPublished(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkEventPublished", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkEventPublished indicates an expected call of MarkEventPublished.
func (mr *MockQuerierMockRecorder) MarkEventPublished(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkEventPublished", reflect.TypeOf((*MockQuerier)(nil).MarkEventPublished), ctx, id)
}

// UpsertLocation mocks base method.
func (m *MockQuerier) UpsertLocation(ctx context.Context, arg db.UpsertLocationParams) (db.DisasterLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertLocation", ctx, arg)
	ret0, _ := ret[0].(db.DisasterLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertLocation indicates an expected call of UpsertLocation.
func (mr *MockQuerierMockRecorder) UpsertLocation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertLocation", reflect.TypeOf((*MockQuerier)(nil).UpsertLocation), ctx, arg)
}

// UpsertLocationStats mocks base method.
func (m *MockQuerier) UpsertLocationStats(ctx context.Context, arg db.UpsertLocationStatsParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertLocationStats", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertLocationStats indicates an expected call of UpsertLocationStats.
func (mr *MockQuerierMockRecorder) UpsertLocationStats(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertLocationStats", reflect.TypeOf((*MockQuerier)(nil).UpsertLocationStats), ctx, arg)
}

// UpsertPhoto mocks base method.
func (m *MockQuerier) UpsertPhoto(ctx context.Context, arg db.UpsertPhotoParams) (db.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertPhoto", ctx, arg)
	ret0, _ := ret[0].(db.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertPhoto indicates an expected call of UpsertPhoto.
func (mr *MockQuerierMockRecorder) UpsertPhoto(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertPhoto", reflect.TypeOf((*MockQuerier)(nil).UpsertPhoto), ctx, arg)
}

// UpsertSiteAssessment mocks base method.
func (m *MockQuerier) UpsertSiteAssessment(ctx context.Context, arg db.UpsertSiteAssessmentParams) (db.SiteAssessment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertSiteAssessment", ctx, arg)
	ret0, _ := ret[0].(db.SiteAssessment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertSiteAssessment indicates an expected call of UpsertSiteAssessment.
func (mr *MockQuerierMockRecorder) UpsertSiteAssessment(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertSiteAssessment", reflect.TypeOf((*MockQuerier)(nil).UpsertSiteAssessment), ctx, arg)
}
