// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForBulkInsertEventSeats implements pgx.CopyFromSource.
type iteratorForBulkInsertEventSeats struct {
	rows                 []BulkInsertEventSeatsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkInsertEventSeats) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkInsertEventSeats) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].EventID,
		r.rows[0].SeatID,
		r.rows[0].SeatOrdinal,
		r.rows[0].Status,
		r.rows[0].Sellable,
		r.rows[0].PriceCents,
	}, nil
}

func (r iteratorForBulkInsertEventSeats) Err() error {
	return nil
}

// BulkInsertEventSeats: cmd/event-publisher's population step, via pgx's
// CopyFrom (sqlc :copyfrom) rather than one INSERT per row — the walk is
// 30,000+ rows for a large venue.
func (q *Queries) BulkInsertEventSeats(ctx context.Context, arg []BulkInsertEventSeatsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"event_seats"}, []string{"event_id", "seat_id", "seat_ordinal", "status", "sellable", "price_cents"}, &iteratorForBulkInsertEventSeats{rows: arg})
}
