// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	EventID       int64              `json:"eventId"`
	VenueID       int64              `json:"venueId"`
	Artist        string             `json:"artist"`
	Title         string             `json:"title"`
	StartsAt      pgtype.Timestamptz `json:"startsAt"`
	OnsaleAt      pgtype.Timestamptz `json:"onsaleAt"`
	HomeRegion    string             `json:"homeRegion"`
	Status        string             `json:"status"`
	LayoutVersion int32              `json:"layoutVersion"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
}

type EventPriceTier struct {
	EventID    int64  `json:"eventId"`
	Tier       string `json:"tier"`
	PriceCents int32  `json:"priceCents"`
}

type EventSeat struct {
	EventID        int64              `json:"eventId"`
	SeatID         int64              `json:"seatId"`
	SeatOrdinal    int32              `json:"seatOrdinal"`
	Status         int16              `json:"status"`
	Sellable       bool               `json:"sellable"`
	HoldID         pgtype.UUID        `json:"holdId"`
	HeldBy         pgtype.Text        `json:"heldBy"`
	HoldExpiresAt  pgtype.Timestamptz `json:"holdExpiresAt"`
	BookingID      pgtype.UUID        `json:"bookingId"`
	PriceCents     int32              `json:"priceCents"`
	HoldPriceCents pgtype.Int4        `json:"holdPriceCents"`
	Version        int32              `json:"version"`
	FenceToken     int64              `json:"fenceToken"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
}

type Seat struct {
	SeatID    int64  `json:"seatId"`
	RowID     int64  `json:"rowId"`
	SeatLabel string `json:"seatLabel"`
	XCoord    int32  `json:"xCoord"`
	YCoord    int32  `json:"yCoord"`
}

type SeatRow struct {
	RowID        int64  `json:"rowId"`
	SectionID    int64  `json:"sectionId"`
	Label        string `json:"label"`
	DisplayOrder int32  `json:"displayOrder"`
}

type Section struct {
	SectionID    int64  `json:"sectionId"`
	VenueID      int64  `json:"venueId"`
	Name         string `json:"name"`
	Tier         string `json:"tier"`
	DisplayOrder int32  `json:"displayOrder"`
	Closed       bool   `json:"closed"`
}

type Venue struct {
	VenueID       int64              `json:"venueId"`
	Name          string             `json:"name"`
	City          string             `json:"city"`
	LayoutVersion int32              `json:"layoutVersion"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
}
