// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DomainEvent struct {
	EventID       uuid.UUID          `json:"eventId"`
	AggregateID   string             `json:"aggregateId"`
	EventType     string             `json:"eventType"`
	SchemaVersion int32              `json:"schemaVersion"`
	Payload       []byte             `json:"payload"`
	PublishedAt   pgtype.Timestamptz `json:"publishedAt"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	OutboxSeq     pgtype.Int8        `json:"outboxSeq"`
}

type Event struct {
	EventID       int64              `json:"eventId"`
	VenueID       int64              `json:"venueId"`
	Artist        string             `json:"artist"`
	Title         string             `json:"title"`
	StartsAt      pgtype.Timestamptz `json:"startsAt"`
	OnsaleAt      pgtype.Timestamptz `json:"onsaleAt"`
	HomeRegion    string             `json:"homeRegion"`
	Status        string             `json:"status"`
	LayoutVersion int32              `json:"layoutVersion"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
}

type EventPriceTier struct {
	EventID    int64  `json:"eventId"`
	Tier       string `json:"tier"`
	PriceCents int32  `json:"priceCents"`
}

type EventSeat struct {
	EventID        int64              `json:"eventId"`
	SeatID         int64              `json:"seatId"`
	SeatOrdinal    int32              `json:"seatOrdinal"`
	Status         int16              `json:"status"`
	Sellable       bool               `json:"sellable"`
	HoldID         pgtype.UUID        `json:"holdId"`
	HeldBy         pgtype.Text        `json:"heldBy"`
	HoldExpiresAt  pgtype.Timestamptz `json:"holdExpiresAt"`
	BookingID      pgtype.UUID        `json:"bookingId"`
	PriceCents     int32              `json:"priceCents"`
	HoldPriceCents pgtype.Int4        `json:"holdPriceCents"`
	Version        int32              `json:"version"`
	FenceToken     int64              `json:"fenceToken"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
}

type HoldsAudit struct {
	ID         int64              `json:"id"`
	HoldID     uuid.UUID          `json:"holdId"`
	EventID    int64              `json:"eventId"`
	SeatID     int64              `json:"seatId"`
	UserSub    string             `json:"userSub"`
	Outcome    string             `json:"outcome"`
	FenceToken pgtype.Int8        `json:"fenceToken"`
	ExpiresAt  pgtype.Timestamptz `json:"expiresAt"`
	LatencyMs  pgtype.Int4        `json:"latencyMs"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
}

type IdempotencyKey struct {
	Key            string             `json:"key"`
	UserSub        string             `json:"userSub"`
	Route          string             `json:"route"`
	RequestHash    string             `json:"requestHash"`
	ResponseStatus pgtype.Int4        `json:"responseStatus"`
	ResponseBody   []byte             `json:"responseBody"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	CompletedAt    pgtype.Timestamptz `json:"completedAt"`
}

type Order struct {
	OrderID       uuid.UUID          `json:"orderId"`
	UserSub       string             `json:"userSub"`
	EventID       int64              `json:"eventId"`
	HoldID        uuid.UUID          `json:"holdId"`
	SeatIds       []int64            `json:"seatIds"`
	AmountCents   int32              `json:"amountCents"`
	Currency      string             `json:"currency"`
	Status        string             `json:"status"`
	Reallocated   bool               `json:"reallocated"`
	FailureCode   pgtype.Text        `json:"failureCode"`
	FailureDetail pgtype.Text        `json:"failureDetail"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
}

type OrderSagaStep struct {
	OrderID   uuid.UUID          `json:"orderId"`
	Step      string             `json:"step"`
	State     string             `json:"state"`
	Attempts  int32              `json:"attempts"`
	LastError pgtype.Text        `json:"lastError"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type Payment struct {
	PaymentID      uuid.UUID          `json:"paymentId"`
	OrderID        uuid.UUID          `json:"orderId"`
	IdempotencyKey string             `json:"idempotencyKey"`
	ProviderRef    pgtype.Text        `json:"providerRef"`
	AmountCents    int32              `json:"amountCents"`
	Status         string             `json:"status"`
	Attempts       int32              `json:"attempts"`
	LastError      pgtype.Text        `json:"lastError"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
}

type ProcessedEvent struct {
	EventID      uuid.UUID          `json:"eventId"`
	ConsumerName string             `json:"consumerName"`
	ProcessedAt  pgtype.Timestamptz `json:"processedAt"`
}

type Refund struct {
	RefundID    uuid.UUID          `json:"refundId"`
	PaymentID   uuid.UUID          `json:"paymentId"`
	ProviderRef pgtype.Text        `json:"providerRef"`
	AmountCents int32              `json:"amountCents"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
}

type Seat struct {
	SeatID    int64  `json:"seatId"`
	RowID     int64  `json:"rowId"`
	SeatLabel string `json:"seatLabel"`
	XCoord    int32  `json:"xCoord"`
	YCoord    int32  `json:"yCoord"`
}

type SeatRow struct {
	RowID        int64  `json:"rowId"`
	SectionID    int64  `json:"sectionId"`
	Label        string `json:"label"`
	DisplayOrder int32  `json:"displayOrder"`
}

type Section struct {
	SectionID    int64  `json:"sectionId"`
	VenueID      int64  `json:"venueId"`
	Name         string `json:"name"`
	Tier         string `json:"tier"`
	DisplayOrder int32  `json:"displayOrder"`
	Closed       bool   `json:"closed"`
}

type Venue struct {
	VenueID       int64              `json:"venueId"`
	Name          string             `json:"name"`
	City          string             `json:"city"`
	LayoutVersion int32              `json:"layoutVersion"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
}

type WaitingRoomAudit struct {
	ID              int64              `json:"id"`
	EventID         int64              `json:"eventId"`
	Rate            float64            `json:"rate"`
	CursorValue     int64              `json:"cursorValue"`
	HoldP99Ms       float64            `json:"holdP99Ms"`
	PoolUtilization float64            `json:"poolUtilization"`
	HoldErrorRate   float64            `json:"holdErrorRate"`
	RedLatency      bool               `json:"redLatency"`
	RedPool         bool               `json:"redPool"`
	RedErrors       bool               `json:"redErrors"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
}

type WsConnection struct {
	ConnectionID   uuid.UUID          `json:"connectionId"`
	EventID        int64              `json:"eventId"`
	UserSub        string             `json:"userSub"`
	ConnectedAt    pgtype.Timestamptz `json:"connectedAt"`
	LastSeqSent    int64              `json:"lastSeqSent"`
	DisconnectedAt pgtype.Timestamptz `json:"disconnectedAt"`
}
