// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acquireHold = `-- name: AcquireHold :many
UPDATE event_seats
   SET status = 1,
       hold_id = $1, held_by = $2,
       hold_expires_at = now() + make_interval(secs => $3::int),
       hold_price_cents = price_cents,
       fence_token = fence_token + 1, version = version + 1, updated_at = now()
 WHERE event_id = $4 AND seat_id = ANY($5::bigint[])
   AND sellable
   AND (status = 0 OR (status IN (1, 3) AND hold_expires_at < now()))
RETURNING seat_id, seat_ordinal, fence_token, hold_expires_at, hold_price_cents
`

type AcquireHoldParams struct {
	HoldID     pgtype.UUID `json:"holdId"`
	UserSub    pgtype.Text `json:"userSub"`
	TtlSeconds int32       `json:"ttlSeconds"`
	EventID    int64       `json:"eventId"`
	SeatIds    []int64     `json:"seatIds"`
}

type AcquireHoldRow struct {
	SeatID         int64              `json:"seatId"`
	SeatOrdinal    int32              `json:"seatOrdinal"`
	FenceToken     int64              `json:"fenceToken"`
	HoldExpiresAt  pgtype.Timestamptz `json:"holdExpiresAt"`
	HoldPriceCents pgtype.Int4        `json:"holdPriceCents"`
}

// AcquireHold: the arbiter. `sellable` gates the CAS so a structurally
// unsellable seat can never be held; the status predicate is passive
// expiry — the WHERE clause IS the guarantee, not a timer.
func (q *Queries) AcquireHold(ctx context.Context, arg AcquireHoldParams) ([]AcquireHoldRow, error) {
	rows, err := q.db.Query(ctx, acquireHold,
		arg.HoldID,
		arg.UserSub,
		arg.TtlSeconds,
		arg.EventID,
		arg.SeatIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AcquireHoldRow
	for rows.Next() {
		var i AcquireHoldRow
		if err := rows.Scan(
			&i.SeatID,
			&i.SeatOrdinal,
			&i.FenceToken,
			&i.HoldExpiresAt,
			&i.HoldPriceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type BulkInsertEventSeatsParams struct {
	EventID     int64 `json:"eventId"`
	SeatID      int64 `json:"seatId"`
	SeatOrdinal int32 `json:"seatOrdinal"`
	Status      int16 `json:"status"`
	Sellable    bool  `json:"sellable"`
	PriceCents  int32 `json:"priceCents"`
}

const closeWSConnection = `-- name: CloseWSConnection :exec
UPDATE ws_connections SET disconnected_at = now() WHERE connection_id = $1
`

func (q *Queries) CloseWSConnection(ctx context.Context, connectionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, closeWSConnection, connectionID)
	return err
}

const confirmSeats = `-- name: ConfirmSeats :execrows
UPDATE event_seats es
   SET status = 2, booking_id = $1, hold_id = NULL,
       held_by = NULL, hold_expires_at = NULL, version = version + 1, updated_at = now()
  FROM unnest($4::bigint[]) WITH ORDINALITY AS s (seat_id, ord)
  JOIN unnest($5::bigint[]) WITH ORDINALITY AS f (fence, ord) ON s.ord = f.ord
 WHERE es.event_id = $2 AND es.seat_id = s.seat_id
   AND es.status IN (1, 3) AND es.hold_id = $3
   AND es.fence_token = f.fence
   AND es.hold_expires_at > now()
`

type ConfirmSeatsParams struct {
	OrderID pgtype.UUID `json:"orderId"`
	EventID int64       `json:"eventId"`
	HoldID  pgtype.UUID `json:"holdId"`
	SeatIds []int64     `json:"seatIds"`
	Fences  []int64     `json:"fences"`
}

// ConfirmSeats: the single most important statement in the whole system.
// fence_token equality (not >=, see fixed gap #3) is the RedLock-question
// answer — a zombie holder whose hold was reclaimed and re-issued fails
// here even if it somehow still holds a matching hold_id.
// Two single-arg unnest()s zipped by WITH ORDINALITY, not the two-array
// unnest(a, b) form — sqlc's own function catalog doesn't model that
// overload even though Postgres itself supports it since 9.4.
func (q *Queries) ConfirmSeats(ctx context.Context, arg ConfirmSeatsParams) (int64, error) {
	result, err := q.db.Exec(ctx, confirmSeats,
		arg.OrderID,
		arg.EventID,
		arg.HoldID,
		arg.SeatIds,
		arg.Fences,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countAvailableSeats = `-- name: CountAvailableSeats :one
SELECT count(*) FROM event_seats WHERE event_id = $1 AND status = 0 AND sellable
`

// CountAvailableSeats: fine at catalog-listing scale (one query per event in
// a <=100-row page); revisit with a materialized per-event counter only if
// this becomes a measured bottleneck.
func (q *Queries) CountAvailableSeats(ctx context.Context, eventID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAvailableSeats, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEventSeats = `-- name: CountEventSeats :one
SELECT count(*) FROM event_seats WHERE event_id = $1
`

func (q *Queries) CountEventSeats(ctx context.Context, eventID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countEventSeats, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (venue_id, artist, title, starts_at, onsale_at, home_region, layout_version)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING event_id, venue_id, artist, title, starts_at, onsale_at, home_region, status, layout_version, created_at
`

type CreateEventParams struct {
	VenueID       int64              `json:"venueId"`
	Artist        string             `json:"artist"`
	Title         string             `json:"title"`
	StartsAt      pgtype.Timestamptz `json:"startsAt"`
	OnsaleAt      pgtype.Timestamptz `json:"onsaleAt"`
	HomeRegion    string             `json:"homeRegion"`
	LayoutVersion int32              `json:"layoutVersion"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.VenueID,
		arg.Artist,
		arg.Title,
		arg.StartsAt,
		arg.OnsaleAt,
		arg.HomeRegion,
		arg.LayoutVersion,
	)
	var i Event
	err := row.Scan(
		&i.EventID,
		&i.VenueID,
		&i.Artist,
		&i.Title,
		&i.StartsAt,
		&i.OnsaleAt,
		&i.HomeRegion,
		&i.Status,
		&i.LayoutVersion,
		&i.CreatedAt,
	)
	return i, err
}

const createEventPriceTier = `-- name: CreateEventPriceTier :exec
INSERT INTO event_price_tiers (event_id, tier, price_cents) VALUES ($1, $2, $3)
`

type CreateEventPriceTierParams struct {
	EventID    int64  `json:"eventId"`
	Tier       string `json:"tier"`
	PriceCents int32  `json:"priceCents"`
}

func (q *Queries) CreateEventPriceTier(ctx context.Context, arg CreateEventPriceTierParams) error {
	_, err := q.db.Exec(ctx, createEventPriceTier, arg.EventID, arg.Tier, arg.PriceCents)
	return err
}

const createOrder = `-- name: CreateOrder :one

INSERT INTO orders (order_id, user_sub, event_id, hold_id, seat_ids, amount_cents)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING order_id, user_sub, event_id, hold_id, seat_ids, amount_cents, currency, status, reallocated, failure_code, failure_detail, created_at, updated_at
`

type CreateOrderParams struct {
	OrderID     uuid.UUID `json:"orderId"`
	UserSub     string    `json:"userSub"`
	EventID     int64     `json:"eventId"`
	HoldID      uuid.UUID `json:"holdId"`
	SeatIds     []int64   `json:"seatIds"`
	AmountCents int32     `json:"amountCents"`
}

// Phase 6: the payment saga (docs/plan.md "The saga").
func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.OrderID,
		arg.UserSub,
		arg.EventID,
		arg.HoldID,
		arg.SeatIds,
		arg.AmountCents,
	)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.UserSub,
		&i.EventID,
		&i.HoldID,
		&i.SeatIds,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.Reallocated,
		&i.FailureCode,
		&i.FailureDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSagaStep = `-- name: CreateSagaStep :exec
INSERT INTO order_saga_steps (order_id, step) VALUES ($1, $2)
`

type CreateSagaStepParams struct {
	OrderID uuid.UUID `json:"orderId"`
	Step    string    `json:"step"`
}

func (q *Queries) CreateSagaStep(ctx context.Context, arg CreateSagaStepParams) error {
	_, err := q.db.Exec(ctx, createSagaStep, arg.OrderID, arg.Step)
	return err
}

const createSeat = `-- name: CreateSeat :one
INSERT INTO seats (row_id, seat_label, x_coord, y_coord)
VALUES ($1, $2, $3, $4)
RETURNING seat_id, row_id, seat_label, x_coord, y_coord
`

type CreateSeatParams struct {
	RowID     int64  `json:"rowId"`
	SeatLabel string `json:"seatLabel"`
	XCoord    int32  `json:"xCoord"`
	YCoord    int32  `json:"yCoord"`
}

func (q *Queries) CreateSeat(ctx context.Context, arg CreateSeatParams) (Seat, error) {
	row := q.db.QueryRow(ctx, createSeat,
		arg.RowID,
		arg.SeatLabel,
		arg.XCoord,
		arg.YCoord,
	)
	var i Seat
	err := row.Scan(
		&i.SeatID,
		&i.RowID,
		&i.SeatLabel,
		&i.XCoord,
		&i.YCoord,
	)
	return i, err
}

const createSeatRow = `-- name: CreateSeatRow :one
INSERT INTO seat_rows (section_id, label, display_order)
VALUES ($1, $2, $3)
RETURNING row_id, section_id, label, display_order
`

type CreateSeatRowParams struct {
	SectionID    int64  `json:"sectionId"`
	Label        string `json:"label"`
	DisplayOrder int32  `json:"displayOrder"`
}

func (q *Queries) CreateSeatRow(ctx context.Context, arg CreateSeatRowParams) (SeatRow, error) {
	row := q.db.QueryRow(ctx, createSeatRow, arg.SectionID, arg.Label, arg.DisplayOrder)
	var i SeatRow
	err := row.Scan(
		&i.RowID,
		&i.SectionID,
		&i.Label,
		&i.DisplayOrder,
	)
	return i, err
}

const createSection = `-- name: CreateSection :one
INSERT INTO sections (venue_id, name, tier, display_order, closed)
VALUES ($1, $2, $3, $4, $5)
RETURNING section_id, venue_id, name, tier, display_order, closed
`

type CreateSectionParams struct {
	VenueID      int64  `json:"venueId"`
	Name         string `json:"name"`
	Tier         string `json:"tier"`
	DisplayOrder int32  `json:"displayOrder"`
	Closed       bool   `json:"closed"`
}

func (q *Queries) CreateSection(ctx context.Context, arg CreateSectionParams) (Section, error) {
	row := q.db.QueryRow(ctx, createSection,
		arg.VenueID,
		arg.Name,
		arg.Tier,
		arg.DisplayOrder,
		arg.Closed,
	)
	var i Section
	err := row.Scan(
		&i.SectionID,
		&i.VenueID,
		&i.Name,
		&i.Tier,
		&i.DisplayOrder,
		&i.Closed,
	)
	return i, err
}

const createVenue = `-- name: CreateVenue :one

INSERT INTO venues (name, city) VALUES ($1, $2)
RETURNING venue_id, name, city, layout_version, created_at
`

type CreateVenueParams struct {
	Name string `json:"name"`
	City string `json:"city"`
}

// Phase 2: venue-template writes (used by scripts/seed-venue) and the
// catalog/availability/pricing read path. Hold/release/confirm CAS queries
// land in Phase 3 alongside internal/inventory.
func (q *Queries) CreateVenue(ctx context.Context, arg CreateVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, createVenue, arg.Name, arg.City)
	var i Venue
	err := row.Scan(
		&i.VenueID,
		&i.Name,
		&i.City,
		&i.LayoutVersion,
		&i.CreatedAt,
	)
	return i, err
}

const extendHold = `-- name: ExtendHold :execrows
UPDATE event_seats
   SET status = 3,
       hold_expires_at = greatest(hold_expires_at, now() + make_interval(secs => $1::int)),
       version = version + 1, updated_at = now()
 WHERE event_id = $2 AND seat_id = ANY($3::bigint[])
   AND status IN (1, 3) AND hold_id = $4 AND hold_expires_at > now()
`

type ExtendHoldParams struct {
	ExtendSeconds int32       `json:"extendSeconds"`
	EventID       int64       `json:"eventId"`
	SeatIds       []int64     `json:"seatIds"`
	HoldID        pgtype.UUID `json:"holdId"`
}

// ExtendHold: called at payment initiation. rowcount < len(seats) means the
// hold already lapsed — the saga must abort BEFORE charging.
func (q *Queries) ExtendHold(ctx context.Context, arg ExtendHoldParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendHold,
		arg.ExtendSeconds,
		arg.EventID,
		arg.SeatIds,
		arg.HoldID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failOrder = `-- name: FailOrder :exec
UPDATE orders SET status = 'FAILED', failure_code = $1,
                   failure_detail = $2, updated_at = now()
WHERE order_id = $3
`

type FailOrderParams struct {
	FailureCode   pgtype.Text `json:"failureCode"`
	FailureDetail pgtype.Text `json:"failureDetail"`
	OrderID       uuid.UUID   `json:"orderId"`
}

func (q *Queries) FailOrder(ctx context.Context, arg FailOrderParams) error {
	_, err := q.db.Exec(ctx, failOrder, arg.FailureCode, arg.FailureDetail, arg.OrderID)
	return err
}

const findCapturedPaymentsMissingOrderOrRefund = `-- name: FindCapturedPaymentsMissingOrderOrRefund :many
SELECT p.payment_id FROM payments p
WHERE p.status = 'CAPTURED'
  AND NOT EXISTS (SELECT 1 FROM orders o WHERE o.order_id = p.order_id AND o.status IN ('CONFIRMED', 'TICKETED'))
  AND NOT EXISTS (SELECT 1 FROM refunds r WHERE r.payment_id = p.payment_id AND r.status = 'COMPLETED')
`

// The money invariant, half 2: a CAPTURED payment with no confirmed order
// and no completed refund — must always be 0 rows.
func (q *Queries) FindCapturedPaymentsMissingOrderOrRefund(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, findCapturedPaymentsMissingOrderOrRefund)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var payment_id uuid.UUID
		if err := rows.Scan(&payment_id); err != nil {
			return nil, err
		}
		items = append(items, payment_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOrdersMissingPayment = `-- name: FindOrdersMissingPayment :many
SELECT o.order_id FROM orders o
LEFT JOIN payments p ON p.order_id = o.order_id AND p.status = 'CAPTURED'
WHERE o.status IN ('CONFIRMED', 'TICKETED') AND p.payment_id IS NULL
`

// The money invariant, half 1: a CONFIRMED/TICKETED order with no
// CAPTURED payment — must always be 0 rows.
func (q *Queries) FindOrdersMissingPayment(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, findOrdersMissingPayment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var order_id uuid.UUID
		if err := rows.Scan(&order_id); err != nil {
			return nil, err
		}
		items = append(items, order_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEvent = `-- name: GetEvent :one
SELECT event_id, venue_id, artist, title, starts_at, onsale_at, home_region, status, layout_version, created_at FROM events WHERE event_id = $1
`

func (q *Queries) GetEvent(ctx context.Context, eventID int64) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, eventID)
	var i Event
	err := row.Scan(
		&i.EventID,
		&i.VenueID,
		&i.Artist,
		&i.Title,
		&i.StartsAt,
		&i.OnsaleAt,
		&i.HomeRegion,
		&i.Status,
		&i.LayoutVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT order_id, user_sub, event_id, hold_id, seat_ids, amount_cents, currency, status, reallocated, failure_code, failure_detail, created_at, updated_at FROM orders WHERE order_id = $1
`

func (q *Queries) GetOrder(ctx context.Context, orderID uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, orderID)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.UserSub,
		&i.EventID,
		&i.HoldID,
		&i.SeatIds,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.Reallocated,
		&i.FailureCode,
		&i.FailureDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByHoldID = `-- name: GetOrderByHoldID :one
SELECT order_id, user_sub, event_id, hold_id, seat_ids, amount_cents, currency, status, reallocated, failure_code, failure_detail, created_at, updated_at FROM orders WHERE hold_id = $1
`

func (q *Queries) GetOrderByHoldID(ctx context.Context, holdID uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByHoldID, holdID)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.UserSub,
		&i.EventID,
		&i.HoldID,
		&i.SeatIds,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.Reallocated,
		&i.FailureCode,
		&i.FailureDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByIdempotencyKey = `-- name: GetPaymentByIdempotencyKey :one
SELECT payment_id, order_id, idempotency_key, provider_ref, amount_cents, status, attempts, last_error, created_at, updated_at FROM payments WHERE idempotency_key = $1
`

func (q *Queries) GetPaymentByIdempotencyKey(ctx context.Context, idempotencyKey string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByIdempotencyKey, idempotencyKey)
	var i Payment
	err := row.Scan(
		&i.PaymentID,
		&i.OrderID,
		&i.IdempotencyKey,
		&i.ProviderRef,
		&i.AmountCents,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSagaStep = `-- name: GetSagaStep :one
SELECT order_id, step, state, attempts, last_error, updated_at FROM order_saga_steps WHERE order_id = $1 AND step = $2
`

type GetSagaStepParams struct {
	OrderID uuid.UUID `json:"orderId"`
	Step    string    `json:"step"`
}

func (q *Queries) GetSagaStep(ctx context.Context, arg GetSagaStepParams) (OrderSagaStep, error) {
	row := q.db.QueryRow(ctx, getSagaStep, arg.OrderID, arg.Step)
	var i OrderSagaStep
	err := row.Scan(
		&i.OrderID,
		&i.Step,
		&i.State,
		&i.Attempts,
		&i.LastError,
		&i.UpdatedAt,
	)
	return i, err
}

const getSeatIDsByOrdinals = `-- name: GetSeatIDsByOrdinals :many

SELECT seat_id, seat_ordinal FROM event_seats
WHERE event_id = $1 AND seat_ordinal = ANY($2::int[])
`

type GetSeatIDsByOrdinalsParams struct {
	EventID  int64   `json:"eventId"`
	Ordinals []int32 `json:"ordinals"`
}

type GetSeatIDsByOrdinalsRow struct {
	SeatID      int64 `json:"seatId"`
	SeatOrdinal int32 `json:"seatOrdinal"`
}

// Phase 3: the correctness core (docs/plan.md "The correctness core").
// Callers MUST pre-sort seat_ids ascending (and fences alongside them for
// ConfirmSeats) — that ordering is what makes deadlock between two
// concurrent multi-seat CAS statements structurally impossible, not just
// unlikely (fixed gap #8).
func (q *Queries) GetSeatIDsByOrdinals(ctx context.Context, arg GetSeatIDsByOrdinalsParams) ([]GetSeatIDsByOrdinalsRow, error) {
	rows, err := q.db.Query(ctx, getSeatIDsByOrdinals, arg.EventID, arg.Ordinals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSeatIDsByOrdinalsRow
	for rows.Next() {
		var i GetSeatIDsByOrdinalsRow
		if err := rows.Scan(&i.SeatID, &i.SeatOrdinal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeatsByHoldID = `-- name: GetSeatsByHoldID :many
SELECT event_id, seat_id, seat_ordinal, held_by, hold_price_cents, hold_expires_at, fence_token
FROM event_seats
WHERE hold_id = $1
ORDER BY seat_id
`

type GetSeatsByHoldIDRow struct {
	EventID        int64              `json:"eventId"`
	SeatID         int64              `json:"seatId"`
	SeatOrdinal    int32              `json:"seatOrdinal"`
	HeldBy         pgtype.Text        `json:"heldBy"`
	HoldPriceCents pgtype.Int4        `json:"holdPriceCents"`
	HoldExpiresAt  pgtype.Timestamptz `json:"holdExpiresAt"`
	FenceToken     int64              `json:"fenceToken"`
}

// GetSeatsByHoldID: the lookup GET/DELETE /holds/{id} and POST
// /holds/{id}/extend need — no separate `holds` table exists, so a hold's
// seats are found by hold_id alone via event_seats_hold_id_idx.
func (q *Queries) GetSeatsByHoldID(ctx context.Context, holdID pgtype.UUID) ([]GetSeatsByHoldIDRow, error) {
	rows, err := q.db.Query(ctx, getSeatsByHoldID, holdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSeatsByHoldIDRow
	for rows.Next() {
		var i GetSeatsByHoldIDRow
		if err := rows.Scan(
			&i.EventID,
			&i.SeatID,
			&i.SeatOrdinal,
			&i.HeldBy,
			&i.HoldPriceCents,
			&i.HoldExpiresAt,
			&i.FenceToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVenue = `-- name: GetVenue :one
SELECT venue_id, name, city, layout_version, created_at FROM venues WHERE venue_id = $1
`

func (q *Queries) GetVenue(ctx context.Context, venueID int64) (Venue, error) {
	row := q.db.QueryRow(ctx, getVenue, venueID)
	var i Venue
	err := row.Scan(
		&i.VenueID,
		&i.Name,
		&i.City,
		&i.LayoutVersion,
		&i.CreatedAt,
	)
	return i, err
}

const insertDomainEvent = `-- name: InsertDomainEvent :exec
INSERT INTO domain_events (event_id, aggregate_id, event_type, schema_version, payload)
VALUES ($1, $2, $3, $4, $5)
`

type InsertDomainEventParams struct {
	EventID       uuid.UUID `json:"eventId"`
	AggregateID   string    `json:"aggregateId"`
	EventType     string    `json:"eventType"`
	SchemaVersion int32     `json:"schemaVersion"`
	Payload       []byte    `json:"payload"`
}

func (q *Queries) InsertDomainEvent(ctx context.Context, arg InsertDomainEventParams) error {
	_, err := q.db.Exec(ctx, insertDomainEvent,
		arg.EventID,
		arg.AggregateID,
		arg.EventType,
		arg.SchemaVersion,
		arg.Payload,
	)
	return err
}

const insertHoldsAudit = `-- name: InsertHoldsAudit :exec
INSERT INTO holds_audit (hold_id, event_id, seat_id, user_sub, outcome, fence_token, expires_at, latency_ms)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8)
`

type InsertHoldsAuditParams struct {
	HoldID     uuid.UUID          `json:"holdId"`
	EventID    int64              `json:"eventId"`
	SeatID     int64              `json:"seatId"`
	UserSub    string             `json:"userSub"`
	Outcome    string             `json:"outcome"`
	FenceToken pgtype.Int8        `json:"fenceToken"`
	ExpiresAt  pgtype.Timestamptz `json:"expiresAt"`
	LatencyMs  pgtype.Int4        `json:"latencyMs"`
}

func (q *Queries) InsertHoldsAudit(ctx context.Context, arg InsertHoldsAuditParams) error {
	_, err := q.db.Exec(ctx, insertHoldsAudit,
		arg.HoldID,
		arg.EventID,
		arg.SeatID,
		arg.UserSub,
		arg.Outcome,
		arg.FenceToken,
		arg.ExpiresAt,
		arg.LatencyMs,
	)
	return err
}

const insertPayment = `-- name: InsertPayment :one
INSERT INTO payments (payment_id, order_id, idempotency_key, amount_cents, status)
VALUES ($1, $2, $3, $4, 'PENDING')
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING payment_id, order_id, idempotency_key, provider_ref, amount_cents, status, attempts, last_error, created_at, updated_at
`

type InsertPaymentParams struct {
	PaymentID      uuid.UUID `json:"paymentId"`
	OrderID        uuid.UUID `json:"orderId"`
	IdempotencyKey string    `json:"idempotencyKey"`
	AmountCents    int32     `json:"amountCents"`
}

func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, insertPayment,
		arg.PaymentID,
		arg.OrderID,
		arg.IdempotencyKey,
		arg.AmountCents,
	)
	var i Payment
	err := row.Scan(
		&i.PaymentID,
		&i.OrderID,
		&i.IdempotencyKey,
		&i.ProviderRef,
		&i.AmountCents,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRefund = `-- name: InsertRefund :one
INSERT INTO refunds (refund_id, payment_id, provider_ref, amount_cents, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING refund_id, payment_id, provider_ref, amount_cents, status, created_at
`

type InsertRefundParams struct {
	RefundID    uuid.UUID   `json:"refundId"`
	PaymentID   uuid.UUID   `json:"paymentId"`
	ProviderRef pgtype.Text `json:"providerRef"`
	AmountCents int32       `json:"amountCents"`
	Status      string      `json:"status"`
}

func (q *Queries) InsertRefund(ctx context.Context, arg InsertRefundParams) (Refund, error) {
	row := q.db.QueryRow(ctx, insertRefund,
		arg.RefundID,
		arg.PaymentID,
		arg.ProviderRef,
		arg.AmountCents,
		arg.Status,
	)
	var i Refund
	err := row.Scan(
		&i.RefundID,
		&i.PaymentID,
		&i.ProviderRef,
		&i.AmountCents,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertWSConnection = `-- name: InsertWSConnection :exec
INSERT INTO ws_connections (connection_id, event_id, user_sub)
VALUES ($1, $2, $3)
`

type InsertWSConnectionParams struct {
	ConnectionID uuid.UUID `json:"connectionId"`
	EventID      int64     `json:"eventId"`
	UserSub      string    `json:"userSub"`
}

func (q *Queries) InsertWSConnection(ctx context.Context, arg InsertWSConnectionParams) error {
	_, err := q.db.Exec(ctx, insertWSConnection, arg.ConnectionID, arg.EventID, arg.UserSub)
	return err
}

const insertWaitingRoomAudit = `-- name: InsertWaitingRoomAudit :exec
INSERT INTO waiting_room_audit
  (event_id, rate, cursor_value, hold_p99_ms, pool_utilization, hold_error_rate,
   red_latency, red_pool, red_errors)
VALUES
  ($1, $2, $3, $4,
   $5, $6,
   $7, $8, $9)
`

type InsertWaitingRoomAuditParams struct {
	EventID         int64   `json:"eventId"`
	Rate            float64 `json:"rate"`
	CursorValue     int64   `json:"cursorValue"`
	HoldP99Ms       float64 `json:"holdP99Ms"`
	PoolUtilization float64 `json:"poolUtilization"`
	HoldErrorRate   float64 `json:"holdErrorRate"`
	RedLatency      bool    `json:"redLatency"`
	RedPool         bool    `json:"redPool"`
	RedErrors       bool    `json:"redErrors"`
}

// Phase 8 (internal/waitingroom): one row per AIMD controller tick — the
// mechanism that lets "the loop closing on real backpressure" be plotted
// from real numbers instead of asserted in prose.
func (q *Queries) InsertWaitingRoomAudit(ctx context.Context, arg InsertWaitingRoomAuditParams) error {
	_, err := q.db.Exec(ctx, insertWaitingRoomAudit,
		arg.EventID,
		arg.Rate,
		arg.CursorValue,
		arg.HoldP99Ms,
		arg.PoolUtilization,
		arg.HoldErrorRate,
		arg.RedLatency,
		arg.RedPool,
		arg.RedErrors,
	)
	return err
}

const listAllEventIDs = `-- name: ListAllEventIDs :many
SELECT event_id FROM events ORDER BY event_id
`

// ListAllEventIDs: cmd/waiting-room-controller's per-tick scan target — at
// local-dev scale (dozens of events) ticking every event every second is
// cheap; a real deployment would scope this to events currently on sale.
func (q *Queries) ListAllEventIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, listAllEventIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var event_id int64
		if err := rows.Scan(&event_id); err != nil {
			return nil, err
		}
		items = append(items, event_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailableForBestAvailable = `-- name: ListAvailableForBestAvailable :many
SELECT es.seat_id, es.seat_ordinal, st.row_id
FROM event_seats es
JOIN seats st ON st.seat_id = es.seat_id
WHERE es.event_id = $1 AND es.status = 0 AND es.sellable
  AND es.price_cents <= $2
ORDER BY es.seat_ordinal
`

type ListAvailableForBestAvailableParams struct {
	EventID       int64 `json:"eventId"`
	MaxPriceCents int32 `json:"maxPriceCents"`
}

type ListAvailableForBestAvailableRow struct {
	SeatID      int64 `json:"seatId"`
	SeatOrdinal int32 `json:"seatOrdinal"`
	RowID       int64 `json:"rowId"`
}

// ListAvailableForBestAvailable: candidate seats for the contiguous-run
// scan (internal/inventory.BestAvailable) — row_id is included because
// ordinals are contiguous ACROSS a whole section, not just within one row
// (decision #2), so a run must be broken at a row boundary in Go, not just
// by ordinal adjacency.
func (q *Queries) ListAvailableForBestAvailable(ctx context.Context, arg ListAvailableForBestAvailableParams) ([]ListAvailableForBestAvailableRow, error) {
	rows, err := q.db.Query(ctx, listAvailableForBestAvailable, arg.EventID, arg.MaxPriceCents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAvailableForBestAvailableRow
	for rows.Next() {
		var i ListAvailableForBestAvailableRow
		if err := rows.Scan(&i.SeatID, &i.SeatOrdinal, &i.RowID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClosedSectionsForEvent = `-- name: ListClosedSectionsForEvent :many
SELECT s.section_id
FROM sections s
JOIN seat_rows r ON r.section_id = s.section_id
JOIN seats st ON st.row_id = r.row_id
JOIN event_seats es ON es.seat_id = st.seat_id AND es.event_id = $1
GROUP BY s.section_id, s.display_order
HAVING bool_and(NOT es.sellable)
ORDER BY s.display_order
`

// A section counts as closed for this event only once every seat in it is
// unsellable — closedSections is denormalized FROM event_seats.sellable,
// never the other way round (docs/plan.md, fixed gap #2).
func (q *Queries) ListClosedSectionsForEvent(ctx context.Context, eventID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listClosedSectionsForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var section_id int64
		if err := rows.Scan(&section_id); err != nil {
			return nil, err
		}
		items = append(items, section_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventPriceTiers = `-- name: ListEventPriceTiers :many
SELECT event_id, tier, price_cents FROM event_price_tiers WHERE event_id = $1 ORDER BY tier
`

func (q *Queries) ListEventPriceTiers(ctx context.Context, eventID int64) ([]EventPriceTier, error) {
	rows, err := q.db.Query(ctx, listEventPriceTiers, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventPriceTier
	for rows.Next() {
		var i EventPriceTier
		if err := rows.Scan(&i.EventID, &i.Tier, &i.PriceCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventSeatsForAvailability = `-- name: ListEventSeatsForAvailability :many
SELECT seat_ordinal, status, sellable
FROM event_seats
WHERE event_id = $1
ORDER BY seat_ordinal
`

type ListEventSeatsForAvailabilityRow struct {
	SeatOrdinal int32 `json:"seatOrdinal"`
	Status      int16 `json:"status"`
	Sellable    bool  `json:"sellable"`
}

// ListEventSeatsForAvailability: the Phase 2 DB-scan path for
// GET /events/{id}/availability — Index Only Scan on event_seats_cover_idx.
// Superseded by the Redis-backed projector path in Phase 7, DB fallback
// kept for when Redis is cold/down.
func (q *Queries) ListEventSeatsForAvailability(ctx context.Context, eventID int64) ([]ListEventSeatsForAvailabilityRow, error) {
	rows, err := q.db.Query(ctx, listEventSeatsForAvailability, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventSeatsForAvailabilityRow
	for rows.Next() {
		var i ListEventSeatsForAvailabilityRow
		if err := rows.Scan(&i.SeatOrdinal, &i.Status, &i.Sellable); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT event_id, venue_id, artist, title, starts_at, onsale_at, home_region, status, layout_version, created_at FROM events
WHERE ($1::text = '' OR title ILIKE '%' || $1 || '%' OR artist ILIKE '%' || $1 || '%')
  AND ($2::bigint = 0 OR event_id > $2)
ORDER BY event_id
LIMIT $3
`

type ListEventsParams struct {
	Search   string `json:"search"`
	AfterID  int64  `json:"afterId"`
	RowLimit int32  `json:"rowLimit"`
}

// ListEvents: simple keyset pagination by event_id, optional trigram search
// over title/artist (pg_trgm GIN-accelerated ILIKE — docs/plan.md decision #8).
func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.Search, arg.AfterID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.EventID,
			&i.VenueID,
			&i.Artist,
			&i.Title,
			&i.StartsAt,
			&i.OnsaleAt,
			&i.HomeRegion,
			&i.Status,
			&i.LayoutVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredHolds = `-- name: ListExpiredHolds :many
SELECT DISTINCT event_id, hold_id
FROM event_seats
WHERE status IN (1, 3) AND hold_expires_at < now() AND hold_id IS NOT NULL
`

type ListExpiredHoldsRow struct {
	EventID int64       `json:"eventId"`
	HoldID  pgtype.UUID `json:"holdId"`
}

// ListExpiredHolds: cmd/hold-reaper's scan target — the ACTIVE release
// (UX freshness only; passive expiry in the CAS predicate is the actual
// correctness guarantee, docs/plan.md decision #2).
func (q *Queries) ListExpiredHolds(ctx context.Context) ([]ListExpiredHoldsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredHolds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiredHoldsRow
	for rows.Next() {
		var i ListExpiredHoldsRow
		if err := rows.Scan(&i.EventID, &i.HoldID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeatIDsForHold = `-- name: ListSeatIDsForHold :many
SELECT seat_id FROM event_seats WHERE event_id = $1 AND hold_id = $2
`

type ListSeatIDsForHoldParams struct {
	EventID int64       `json:"eventId"`
	HoldID  pgtype.UUID `json:"holdId"`
}

func (q *Queries) ListSeatIDsForHold(ctx context.Context, arg ListSeatIDsForHoldParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listSeatIDsForHold, arg.EventID, arg.HoldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var seat_id int64
		if err := rows.Scan(&seat_id); err != nil {
			return nil, err
		}
		items = append(items, seat_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeatOrdinalsByEvent = `-- name: ListSeatOrdinalsByEvent :many
SELECT seat_id, seat_ordinal FROM event_seats WHERE event_id = $1
`

type ListSeatOrdinalsByEventRow struct {
	SeatID      int64 `json:"seatId"`
	SeatOrdinal int32 `json:"seatOrdinal"`
}

// ListSeatOrdinalsByEvent: the seat_id -> ordinal map the projector caches
// per event_id (in-memory, rebuilt on restart) — domain event payloads key
// by seat_id (the internal identity), but every wire structure (bitset,
// deltas) is ordinal-indexed (docs/plan.md decision #5).
func (q *Queries) ListSeatOrdinalsByEvent(ctx context.Context, eventID int64) ([]ListSeatOrdinalsByEventRow, error) {
	rows, err := q.db.Query(ctx, listSeatOrdinalsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeatOrdinalsByEventRow
	for rows.Next() {
		var i ListSeatOrdinalsByEventRow
		if err := rows.Scan(&i.SeatID, &i.SeatOrdinal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStuckOrders = `-- name: ListStuckOrders :many
SELECT order_id FROM orders
WHERE status IN ('PENDING', 'AUTHORIZING', 'CONFIRMING') AND updated_at < now() - make_interval(secs => $1::int)
ORDER BY created_at
LIMIT $2
`

type ListStuckOrdersParams struct {
	StuckAfterSeconds int32 `json:"stuckAfterSeconds"`
	RowLimit          int32 `json:"rowLimit"`
}

func (q *Queries) ListStuckOrders(ctx context.Context, arg ListStuckOrdersParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listStuckOrders, arg.StuckAfterSeconds, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var order_id uuid.UUID
		if err := rows.Scan(&order_id); err != nil {
			return nil, err
		}
		items = append(items, order_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStuckPayments = `-- name: ListStuckPayments :many
SELECT payment_id, order_id, idempotency_key, provider_ref, amount_cents, status, attempts, last_error, created_at, updated_at FROM payments
WHERE status IN ('PENDING', 'UNKNOWN') AND created_at < now() - make_interval(secs => $1::int)
ORDER BY created_at
LIMIT $2
`

type ListStuckPaymentsParams struct {
	StuckAfterSeconds int32 `json:"stuckAfterSeconds"`
	RowLimit          int32 `json:"rowLimit"`
}

func (q *Queries) ListStuckPayments(ctx context.Context, arg ListStuckPaymentsParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listStuckPayments, arg.StuckAfterSeconds, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.PaymentID,
			&i.OrderID,
			&i.IdempotencyKey,
			&i.ProviderRef,
			&i.AmountCents,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnprocessedDomainEvents = `-- name: ListUnprocessedDomainEvents :many
SELECT de.event_id, de.aggregate_id, de.event_type, de.schema_version, de.payload, de.created_at
FROM domain_events de
WHERE de.event_type IN ('seat.held', 'seat.released', 'seat.booked')
  AND NOT EXISTS (
    SELECT 1 FROM processed_events pe
    WHERE pe.event_id = de.event_id AND pe.consumer_name = $1
  )
ORDER BY de.outbox_seq
LIMIT $2
`

type ListUnprocessedDomainEventsParams struct {
	ConsumerName string `json:"consumerName"`
	RowLimit     int32  `json:"rowLimit"`
}

type ListUnprocessedDomainEventsRow struct {
	EventID       uuid.UUID          `json:"eventId"`
	AggregateID   string             `json:"aggregateId"`
	EventType     string             `json:"eventType"`
	SchemaVersion int32              `json:"schemaVersion"`
	Payload       []byte             `json:"payload"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
}

// Phase 7 (internal/projector): domain events not yet applied by THIS
// consumer. processed_events dedup is scoped to (event_id, consumer_name)
// (migration 0005's comment), so the projector can replay independently of
// the EventBridge outbox relay — a crash mid-batch just re-applies from the
// same point, and the bitset write is itself idempotent (see projector.go).
// outbox_seq, NOT created_at (migration 0008): created_at alone is not a
// strict total order under rapid sequential inserts, and this consumer's
// correctness genuinely depends on applying transitions in real order —
// unlike the outbox relay, which doesn't care about delivery order.
func (q *Queries) ListUnprocessedDomainEvents(ctx context.Context, arg ListUnprocessedDomainEventsParams) ([]ListUnprocessedDomainEventsRow, error) {
	rows, err := q.db.Query(ctx, listUnprocessedDomainEvents, arg.ConsumerName, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnprocessedDomainEventsRow
	for rows.Next() {
		var i ListUnprocessedDomainEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.AggregateID,
			&i.EventType,
			&i.SchemaVersion,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnpublishedDomainEvents = `-- name: ListUnpublishedDomainEvents :many
SELECT event_id, aggregate_id, event_type, schema_version, payload
FROM domain_events
WHERE published_at IS NULL
ORDER BY outbox_seq
LIMIT $1
`

type ListUnpublishedDomainEventsRow struct {
	EventID       uuid.UUID `json:"eventId"`
	AggregateID   string    `json:"aggregateId"`
	EventType     string    `json:"eventType"`
	SchemaVersion int32     `json:"schemaVersion"`
	Payload       []byte    `json:"payload"`
}

func (q *Queries) ListUnpublishedDomainEvents(ctx context.Context, rowLimit int32) ([]ListUnpublishedDomainEventsRow, error) {
	rows, err := q.db.Query(ctx, listUnpublishedDomainEvents, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnpublishedDomainEventsRow
	for rows.Next() {
		var i ListUnpublishedDomainEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.AggregateID,
			&i.EventType,
			&i.SchemaVersion,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVenueSeatsOrdered = `-- name: ListVenueSeatsOrdered :many
SELECT
    s.section_id, s.name AS section_name, s.tier AS section_tier,
    s.display_order AS section_display_order, s.closed AS section_closed,
    r.row_id, r.label AS row_label, r.display_order AS row_display_order,
    st.seat_id, st.seat_label, st.x_coord, st.y_coord
FROM sections s
JOIN seat_rows r ON r.section_id = s.section_id
JOIN seats st ON st.row_id = r.row_id
WHERE s.venue_id = $1
ORDER BY s.display_order, r.display_order, st.seat_label
`

type ListVenueSeatsOrderedRow struct {
	SectionID           int64  `json:"sectionId"`
	SectionName         string `json:"sectionName"`
	SectionTier         string `json:"sectionTier"`
	SectionDisplayOrder int32  `json:"sectionDisplayOrder"`
	SectionClosed       bool   `json:"sectionClosed"`
	RowID               int64  `json:"rowId"`
	RowLabel            string `json:"rowLabel"`
	RowDisplayOrder     int32  `json:"rowDisplayOrder"`
	SeatID              int64  `json:"seatId"`
	SeatLabel           string `json:"seatLabel"`
	XCoord              int32  `json:"xCoord"`
	YCoord              int32  `json:"yCoord"`
}

// ListVenueSeatsOrdered drives both cmd/event-publisher's ordinal
// assignment and layout.json/seats.bin rendering from the SAME walk, in the
// SAME order (section.display_order, row.display_order, seat_label) — so
// the DB's ordinal assignment and the static layout files can never
// disagree (docs/plan.md "Event publish pipeline").
func (q *Queries) ListVenueSeatsOrdered(ctx context.Context, venueID int64) ([]ListVenueSeatsOrderedRow, error) {
	rows, err := q.db.Query(ctx, listVenueSeatsOrdered, venueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVenueSeatsOrderedRow
	for rows.Next() {
		var i ListVenueSeatsOrderedRow
		if err := rows.Scan(
			&i.SectionID,
			&i.SectionName,
			&i.SectionTier,
			&i.SectionDisplayOrder,
			&i.SectionClosed,
			&i.RowID,
			&i.RowLabel,
			&i.RowDisplayOrder,
			&i.SeatID,
			&i.SeatLabel,
			&i.XCoord,
			&i.YCoord,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaitingRoomAudit = `-- name: ListWaitingRoomAudit :many
SELECT id, event_id, rate, cursor_value, hold_p99_ms, pool_utilization, hold_error_rate, red_latency, red_pool, red_errors, created_at FROM waiting_room_audit WHERE event_id = $1 ORDER BY id
`

func (q *Queries) ListWaitingRoomAudit(ctx context.Context, eventID int64) ([]WaitingRoomAudit, error) {
	rows, err := q.db.Query(ctx, listWaitingRoomAudit, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WaitingRoomAudit
	for rows.Next() {
		var i WaitingRoomAudit
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Rate,
			&i.CursorValue,
			&i.HoldP99Ms,
			&i.PoolUtilization,
			&i.HoldErrorRate,
			&i.RedLatency,
			&i.RedPool,
			&i.RedErrors,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDomainEventPublished = `-- name: MarkDomainEventPublished :exec
UPDATE domain_events SET published_at = now() WHERE event_id = $1
`

func (q *Queries) MarkDomainEventPublished(ctx context.Context, eventID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markDomainEventPublished, eventID)
	return err
}

const markEventProcessed = `-- name: MarkEventProcessed :exec
INSERT INTO processed_events (event_id, consumer_name)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type MarkEventProcessedParams struct {
	EventID      uuid.UUID `json:"eventId"`
	ConsumerName string    `json:"consumerName"`
}

func (q *Queries) MarkEventProcessed(ctx context.Context, arg MarkEventProcessedParams) error {
	_, err := q.db.Exec(ctx, markEventProcessed, arg.EventID, arg.ConsumerName)
	return err
}

const minEventPriceCents = `-- name: MinEventPriceCents :one
SELECT min(price_cents)::int FROM event_price_tiers WHERE event_id = $1
`

func (q *Queries) MinEventPriceCents(ctx context.Context, eventID int64) (int32, error) {
	row := q.db.QueryRow(ctx, minEventPriceCents, eventID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const reallocateOrder = `-- name: ReallocateOrder :exec
UPDATE orders SET hold_id = $1, seat_ids = $2,
                   reallocated = true, updated_at = now()
WHERE order_id = $3
`

type ReallocateOrderParams struct {
	HoldID  uuid.UUID `json:"holdId"`
	SeatIds []int64   `json:"seatIds"`
	OrderID uuid.UUID `json:"orderId"`
}

func (q *Queries) ReallocateOrder(ctx context.Context, arg ReallocateOrderParams) error {
	_, err := q.db.Exec(ctx, reallocateOrder, arg.HoldID, arg.SeatIds, arg.OrderID)
	return err
}

const releaseHold = `-- name: ReleaseHold :execrows
UPDATE event_seats
   SET status = 0, hold_id = NULL, held_by = NULL, hold_expires_at = NULL, hold_price_cents = NULL,
       version = version + 1, updated_at = now()
 WHERE event_id = $1 AND seat_id = ANY($2::bigint[])
   AND status IN (1, 3) AND hold_id = $3
`

type ReleaseHoldParams struct {
	EventID int64       `json:"eventId"`
	SeatIds []int64     `json:"seatIds"`
	HoldID  pgtype.UUID `json:"holdId"`
}

// ReleaseHold: idempotent by construction — rowcount 0 is success (the
// hold was already gone), not an error.
func (q *Queries) ReleaseHold(ctx context.Context, arg ReleaseHoldParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseHold, arg.EventID, arg.SeatIds, arg.HoldID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setEventOnSale = `-- name: SetEventOnSale :exec
UPDATE events SET status = 'ON_SALE' WHERE event_id = $1
`

func (q *Queries) SetEventOnSale(ctx context.Context, eventID int64) error {
	_, err := q.db.Exec(ctx, setEventOnSale, eventID)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders SET status = $1, updated_at = now() WHERE order_id = $2
`

type UpdateOrderStatusParams struct {
	Status  string    `json:"status"`
	OrderID uuid.UUID `json:"orderId"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.Status, arg.OrderID)
	return err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE payments SET status = $1, provider_ref = $2,
                     last_error = $3, attempts = attempts + 1, updated_at = now()
WHERE payment_id = $4
`

type UpdatePaymentStatusParams struct {
	Status      string      `json:"status"`
	ProviderRef pgtype.Text `json:"providerRef"`
	LastError   pgtype.Text `json:"lastError"`
	PaymentID   uuid.UUID   `json:"paymentId"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.Exec(ctx, updatePaymentStatus,
		arg.Status,
		arg.ProviderRef,
		arg.LastError,
		arg.PaymentID,
	)
	return err
}

const updateSagaStep = `-- name: UpdateSagaStep :exec
UPDATE order_saga_steps SET state = $1, last_error = $2,
                             attempts = attempts + 1, updated_at = now()
WHERE order_id = $3 AND step = $4
`

type UpdateSagaStepParams struct {
	State     string      `json:"state"`
	LastError pgtype.Text `json:"lastError"`
	OrderID   uuid.UUID   `json:"orderId"`
	Step      string      `json:"step"`
}

func (q *Queries) UpdateSagaStep(ctx context.Context, arg UpdateSagaStepParams) error {
	_, err := q.db.Exec(ctx, updateSagaStep,
		arg.State,
		arg.LastError,
		arg.OrderID,
		arg.Step,
	)
	return err
}

const updateWSConnectionSeq = `-- name: UpdateWSConnectionSeq :exec
UPDATE ws_connections SET last_seq_sent = $1 WHERE connection_id = $2
`

type UpdateWSConnectionSeqParams struct {
	LastSeqSent  int64     `json:"lastSeqSent"`
	ConnectionID uuid.UUID `json:"connectionId"`
}

func (q *Queries) UpdateWSConnectionSeq(ctx context.Context, arg UpdateWSConnectionSeqParams) error {
	_, err := q.db.Exec(ctx, updateWSConnectionSeq, arg.LastSeqSent, arg.ConnectionID)
	return err
}
