// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// AcquireHold: the arbiter. `sellable` gates the CAS so a structurally
	// unsellable seat can never be held; the status predicate is passive
	// expiry — the WHERE clause IS the guarantee, not a timer.
	AcquireHold(ctx context.Context, arg AcquireHoldParams) ([]AcquireHoldRow, error)
	// BulkInsertEventSeats: cmd/event-publisher's population step, via pgx's
	// CopyFrom (sqlc :copyfrom) rather than one INSERT per row — the walk is
	// 30,000+ rows for a large venue.
	BulkInsertEventSeats(ctx context.Context, arg []BulkInsertEventSeatsParams) (int64, error)
	CloseWSConnection(ctx context.Context, connectionID uuid.UUID) error
	// ConfirmSeats: the single most important statement in the whole system.
	// fence_token equality (not >=, see fixed gap #3) is the RedLock-question
	// answer — a zombie holder whose hold was reclaimed and re-issued fails
	// here even if it somehow still holds a matching hold_id.
	// Two single-arg unnest()s zipped by WITH ORDINALITY, not the two-array
	// unnest(a, b) form — sqlc's own function catalog doesn't model that
	// overload even though Postgres itself supports it since 9.4.
	ConfirmSeats(ctx context.Context, arg ConfirmSeatsParams) (int64, error)
	// CountAvailableSeats: fine at catalog-listing scale (one query per event in
	// a <=100-row page); revisit with a materialized per-event counter only if
	// this becomes a measured bottleneck.
	CountAvailableSeats(ctx context.Context, eventID int64) (int64, error)
	CountEventSeats(ctx context.Context, eventID int64) (int64, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateEventPriceTier(ctx context.Context, arg CreateEventPriceTierParams) error
	// Phase 6: the payment saga (docs/plan.md "The saga").
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateSagaStep(ctx context.Context, arg CreateSagaStepParams) error
	CreateSeat(ctx context.Context, arg CreateSeatParams) (Seat, error)
	CreateSeatRow(ctx context.Context, arg CreateSeatRowParams) (SeatRow, error)
	CreateSection(ctx context.Context, arg CreateSectionParams) (Section, error)
	// Phase 2: venue-template writes (used by scripts/seed-venue) and the
	// catalog/availability/pricing read path. Hold/release/confirm CAS queries
	// land in Phase 3 alongside internal/inventory.
	CreateVenue(ctx context.Context, arg CreateVenueParams) (Venue, error)
	// ExtendHold: called at payment initiation. rowcount < len(seats) means the
	// hold already lapsed — the saga must abort BEFORE charging.
	ExtendHold(ctx context.Context, arg ExtendHoldParams) (int64, error)
	FailOrder(ctx context.Context, arg FailOrderParams) error
	// The money invariant, half 2: a CAPTURED payment with no confirmed order
	// and no completed refund — must always be 0 rows.
	FindCapturedPaymentsMissingOrderOrRefund(ctx context.Context) ([]uuid.UUID, error)
	// The money invariant, half 1: a CONFIRMED/TICKETED order with no
	// CAPTURED payment — must always be 0 rows.
	FindOrdersMissingPayment(ctx context.Context) ([]uuid.UUID, error)
	GetEvent(ctx context.Context, eventID int64) (Event, error)
	GetOrder(ctx context.Context, orderID uuid.UUID) (Order, error)
	GetOrderByHoldID(ctx context.Context, holdID uuid.UUID) (Order, error)
	GetPaymentByIdempotencyKey(ctx context.Context, idempotencyKey string) (Payment, error)
	GetSagaStep(ctx context.Context, arg GetSagaStepParams) (OrderSagaStep, error)
	// Phase 3: the correctness core (docs/plan.md "The correctness core").
	// Callers MUST pre-sort seat_ids ascending (and fences alongside them for
	// ConfirmSeats) — that ordering is what makes deadlock between two
	// concurrent multi-seat CAS statements structurally impossible, not just
	// unlikely (fixed gap #8).
	GetSeatIDsByOrdinals(ctx context.Context, arg GetSeatIDsByOrdinalsParams) ([]GetSeatIDsByOrdinalsRow, error)
	// GetSeatsByHoldID: the lookup GET/DELETE /holds/{id} and POST
	// /holds/{id}/extend need — no separate `holds` table exists, so a hold's
	// seats are found by hold_id alone via event_seats_hold_id_idx.
	GetSeatsByHoldID(ctx context.Context, holdID pgtype.UUID) ([]GetSeatsByHoldIDRow, error)
	GetVenue(ctx context.Context, venueID int64) (Venue, error)
	InsertDomainEvent(ctx context.Context, arg InsertDomainEventParams) error
	InsertHoldsAudit(ctx context.Context, arg InsertHoldsAuditParams) error
	InsertPayment(ctx context.Context, arg InsertPaymentParams) (Payment, error)
	InsertRefund(ctx context.Context, arg InsertRefundParams) (Refund, error)
	InsertWSConnection(ctx context.Context, arg InsertWSConnectionParams) error
	// Phase 8 (internal/waitingroom): one row per AIMD controller tick — the
	// mechanism that lets "the loop closing on real backpressure" be plotted
	// from real numbers instead of asserted in prose.
	InsertWaitingRoomAudit(ctx context.Context, arg InsertWaitingRoomAuditParams) error
	// ListAllEventIDs: cmd/waiting-room-controller's per-tick scan target — at
	// local-dev scale (dozens of events) ticking every event every second is
	// cheap; a real deployment would scope this to events currently on sale.
	ListAllEventIDs(ctx context.Context) ([]int64, error)
	// ListAvailableForBestAvailable: candidate seats for the contiguous-run
	// scan (internal/inventory.BestAvailable) — row_id is included because
	// ordinals are contiguous ACROSS a whole section, not just within one row
	// (decision #2), so a run must be broken at a row boundary in Go, not just
	// by ordinal adjacency.
	ListAvailableForBestAvailable(ctx context.Context, arg ListAvailableForBestAvailableParams) ([]ListAvailableForBestAvailableRow, error)
	// A section counts as closed for this event only once every seat in it is
	// unsellable — closedSections is denormalized FROM event_seats.sellable,
	// never the other way round (docs/plan.md, fixed gap #2).
	ListClosedSectionsForEvent(ctx context.Context, eventID int64) ([]int64, error)
	ListEventPriceTiers(ctx context.Context, eventID int64) ([]EventPriceTier, error)
	// ListEventSeatsForAvailability: the Phase 2 DB-scan path for
	// GET /events/{id}/availability — Index Only Scan on event_seats_cover_idx.
	// Superseded by the Redis-backed projector path in Phase 7, DB fallback
	// kept for when Redis is cold/down.
	ListEventSeatsForAvailability(ctx context.Context, eventID int64) ([]ListEventSeatsForAvailabilityRow, error)
	// ListEvents: simple keyset pagination by event_id, optional trigram search
	// over title/artist (pg_trgm GIN-accelerated ILIKE — docs/plan.md decision #8).
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	// ListExpiredHolds: cmd/hold-reaper's scan target — the ACTIVE release
	// (UX freshness only; passive expiry in the CAS predicate is the actual
	// correctness guarantee, docs/plan.md decision #2).
	ListExpiredHolds(ctx context.Context) ([]ListExpiredHoldsRow, error)
	ListSeatIDsForHold(ctx context.Context, arg ListSeatIDsForHoldParams) ([]int64, error)
	// ListSeatOrdinalsByEvent: the seat_id -> ordinal map the projector caches
	// per event_id (in-memory, rebuilt on restart) — domain event payloads key
	// by seat_id (the internal identity), but every wire structure (bitset,
	// deltas) is ordinal-indexed (docs/plan.md decision #5).
	ListSeatOrdinalsByEvent(ctx context.Context, eventID int64) ([]ListSeatOrdinalsByEventRow, error)
	ListStuckOrders(ctx context.Context, arg ListStuckOrdersParams) ([]uuid.UUID, error)
	ListStuckPayments(ctx context.Context, arg ListStuckPaymentsParams) ([]Payment, error)
	// Phase 7 (internal/projector): domain events not yet applied by THIS
	// consumer. processed_events dedup is scoped to (event_id, consumer_name)
	// (migration 0005's comment), so the projector can replay independently of
	// the EventBridge outbox relay — a crash mid-batch just re-applies from the
	// same point, and the bitset write is itself idempotent (see projector.go).
	// outbox_seq, NOT created_at (migration 0008): created_at alone is not a
	// strict total order under rapid sequential inserts, and this consumer's
	// correctness genuinely depends on applying transitions in real order —
	// unlike the outbox relay, which doesn't care about delivery order.
	ListUnprocessedDomainEvents(ctx context.Context, arg ListUnprocessedDomainEventsParams) ([]ListUnprocessedDomainEventsRow, error)
	ListUnpublishedDomainEvents(ctx context.Context, rowLimit int32) ([]ListUnpublishedDomainEventsRow, error)
	// ListVenueSeatsOrdered drives both cmd/event-publisher's ordinal
	// assignment and layout.json/seats.bin rendering from the SAME walk, in the
	// SAME order (section.display_order, row.display_order, seat_label) — so
	// the DB's ordinal assignment and the static layout files can never
	// disagree (docs/plan.md "Event publish pipeline").
	ListVenueSeatsOrdered(ctx context.Context, venueID int64) ([]ListVenueSeatsOrderedRow, error)
	ListWaitingRoomAudit(ctx context.Context, eventID int64) ([]WaitingRoomAudit, error)
	MarkDomainEventPublished(ctx context.Context, eventID uuid.UUID) error
	MarkEventProcessed(ctx context.Context, arg MarkEventProcessedParams) error
	MinEventPriceCents(ctx context.Context, eventID int64) (int32, error)
	ReallocateOrder(ctx context.Context, arg ReallocateOrderParams) error
	// ReleaseHold: idempotent by construction — rowcount 0 is success (the
	// hold was already gone), not an error.
	ReleaseHold(ctx context.Context, arg ReleaseHoldParams) (int64, error)
	SetEventOnSale(ctx context.Context, eventID int64) error
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error
	UpdateSagaStep(ctx context.Context, arg UpdateSagaStepParams) error
	UpdateWSConnectionSeq(ctx context.Context, arg UpdateWSConnectionSeqParams) error
}

var _ Querier = (*Queries)(nil)
