// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BulkInsertEventSeatsParams struct {
	EventID     int64 `json:"eventId"`
	SeatID      int64 `json:"seatId"`
	SeatOrdinal int32 `json:"seatOrdinal"`
	Status      int16 `json:"status"`
	Sellable    bool  `json:"sellable"`
	PriceCents  int32 `json:"priceCents"`
}

const countEventSeats = `-- name: CountEventSeats :one
SELECT count(*) FROM event_seats WHERE event_id = $1
`

func (q *Queries) CountEventSeats(ctx context.Context, eventID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countEventSeats, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (venue_id, artist, title, starts_at, onsale_at, home_region, layout_version)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING event_id, venue_id, artist, title, starts_at, onsale_at, home_region, status, layout_version, created_at
`

type CreateEventParams struct {
	VenueID       int64              `json:"venueId"`
	Artist        string             `json:"artist"`
	Title         string             `json:"title"`
	StartsAt      pgtype.Timestamptz `json:"startsAt"`
	OnsaleAt      pgtype.Timestamptz `json:"onsaleAt"`
	HomeRegion    string             `json:"homeRegion"`
	LayoutVersion int32              `json:"layoutVersion"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.VenueID,
		arg.Artist,
		arg.Title,
		arg.StartsAt,
		arg.OnsaleAt,
		arg.HomeRegion,
		arg.LayoutVersion,
	)
	var i Event
	err := row.Scan(
		&i.EventID,
		&i.VenueID,
		&i.Artist,
		&i.Title,
		&i.StartsAt,
		&i.OnsaleAt,
		&i.HomeRegion,
		&i.Status,
		&i.LayoutVersion,
		&i.CreatedAt,
	)
	return i, err
}

const createEventPriceTier = `-- name: CreateEventPriceTier :exec
INSERT INTO event_price_tiers (event_id, tier, price_cents) VALUES ($1, $2, $3)
`

type CreateEventPriceTierParams struct {
	EventID    int64  `json:"eventId"`
	Tier       string `json:"tier"`
	PriceCents int32  `json:"priceCents"`
}

func (q *Queries) CreateEventPriceTier(ctx context.Context, arg CreateEventPriceTierParams) error {
	_, err := q.db.Exec(ctx, createEventPriceTier, arg.EventID, arg.Tier, arg.PriceCents)
	return err
}

const createSeat = `-- name: CreateSeat :one
INSERT INTO seats (row_id, seat_label, x_coord, y_coord)
VALUES ($1, $2, $3, $4)
RETURNING seat_id, row_id, seat_label, x_coord, y_coord
`

type CreateSeatParams struct {
	RowID     int64  `json:"rowId"`
	SeatLabel string `json:"seatLabel"`
	XCoord    int32  `json:"xCoord"`
	YCoord    int32  `json:"yCoord"`
}

func (q *Queries) CreateSeat(ctx context.Context, arg CreateSeatParams) (Seat, error) {
	row := q.db.QueryRow(ctx, createSeat,
		arg.RowID,
		arg.SeatLabel,
		arg.XCoord,
		arg.YCoord,
	)
	var i Seat
	err := row.Scan(
		&i.SeatID,
		&i.RowID,
		&i.SeatLabel,
		&i.XCoord,
		&i.YCoord,
	)
	return i, err
}

const createSeatRow = `-- name: CreateSeatRow :one
INSERT INTO seat_rows (section_id, label, display_order)
VALUES ($1, $2, $3)
RETURNING row_id, section_id, label, display_order
`

type CreateSeatRowParams struct {
	SectionID    int64  `json:"sectionId"`
	Label        string `json:"label"`
	DisplayOrder int32  `json:"displayOrder"`
}

func (q *Queries) CreateSeatRow(ctx context.Context, arg CreateSeatRowParams) (SeatRow, error) {
	row := q.db.QueryRow(ctx, createSeatRow, arg.SectionID, arg.Label, arg.DisplayOrder)
	var i SeatRow
	err := row.Scan(
		&i.RowID,
		&i.SectionID,
		&i.Label,
		&i.DisplayOrder,
	)
	return i, err
}

const createSection = `-- name: CreateSection :one
INSERT INTO sections (venue_id, name, tier, display_order, closed)
VALUES ($1, $2, $3, $4, $5)
RETURNING section_id, venue_id, name, tier, display_order, closed
`

type CreateSectionParams struct {
	VenueID      int64  `json:"venueId"`
	Name         string `json:"name"`
	Tier         string `json:"tier"`
	DisplayOrder int32  `json:"displayOrder"`
	Closed       bool   `json:"closed"`
}

func (q *Queries) CreateSection(ctx context.Context, arg CreateSectionParams) (Section, error) {
	row := q.db.QueryRow(ctx, createSection,
		arg.VenueID,
		arg.Name,
		arg.Tier,
		arg.DisplayOrder,
		arg.Closed,
	)
	var i Section
	err := row.Scan(
		&i.SectionID,
		&i.VenueID,
		&i.Name,
		&i.Tier,
		&i.DisplayOrder,
		&i.Closed,
	)
	return i, err
}

const createVenue = `-- name: CreateVenue :one

INSERT INTO venues (name, city) VALUES ($1, $2)
RETURNING venue_id, name, city, layout_version, created_at
`

type CreateVenueParams struct {
	Name string `json:"name"`
	City string `json:"city"`
}

// Phase 2: venue-template writes (used by scripts/seed-venue) and the
// catalog/availability/pricing read path. Hold/release/confirm CAS queries
// land in Phase 3 alongside internal/inventory.
func (q *Queries) CreateVenue(ctx context.Context, arg CreateVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, createVenue, arg.Name, arg.City)
	var i Venue
	err := row.Scan(
		&i.VenueID,
		&i.Name,
		&i.City,
		&i.LayoutVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT event_id, venue_id, artist, title, starts_at, onsale_at, home_region, status, layout_version, created_at FROM events WHERE event_id = $1
`

func (q *Queries) GetEvent(ctx context.Context, eventID int64) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, eventID)
	var i Event
	err := row.Scan(
		&i.EventID,
		&i.VenueID,
		&i.Artist,
		&i.Title,
		&i.StartsAt,
		&i.OnsaleAt,
		&i.HomeRegion,
		&i.Status,
		&i.LayoutVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getVenue = `-- name: GetVenue :one
SELECT venue_id, name, city, layout_version, created_at FROM venues WHERE venue_id = $1
`

func (q *Queries) GetVenue(ctx context.Context, venueID int64) (Venue, error) {
	row := q.db.QueryRow(ctx, getVenue, venueID)
	var i Venue
	err := row.Scan(
		&i.VenueID,
		&i.Name,
		&i.City,
		&i.LayoutVersion,
		&i.CreatedAt,
	)
	return i, err
}

const listClosedSectionsForEvent = `-- name: ListClosedSectionsForEvent :many
SELECT s.section_id
FROM sections s
JOIN seat_rows r ON r.section_id = s.section_id
JOIN seats st ON st.row_id = r.row_id
JOIN event_seats es ON es.seat_id = st.seat_id AND es.event_id = $1
GROUP BY s.section_id
HAVING bool_and(NOT es.sellable)
`

// A section counts as closed for this event only once every seat in it is
// unsellable — closedSections is denormalized FROM event_seats.sellable,
// never the other way round (docs/plan.md, fixed gap #2).
func (q *Queries) ListClosedSectionsForEvent(ctx context.Context, eventID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listClosedSectionsForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var section_id int64
		if err := rows.Scan(&section_id); err != nil {
			return nil, err
		}
		items = append(items, section_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventPriceTiers = `-- name: ListEventPriceTiers :many
SELECT event_id, tier, price_cents FROM event_price_tiers WHERE event_id = $1 ORDER BY tier
`

func (q *Queries) ListEventPriceTiers(ctx context.Context, eventID int64) ([]EventPriceTier, error) {
	rows, err := q.db.Query(ctx, listEventPriceTiers, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventPriceTier
	for rows.Next() {
		var i EventPriceTier
		if err := rows.Scan(&i.EventID, &i.Tier, &i.PriceCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventSeatsForAvailability = `-- name: ListEventSeatsForAvailability :many
SELECT seat_ordinal, status, sellable
FROM event_seats
WHERE event_id = $1
ORDER BY seat_ordinal
`

type ListEventSeatsForAvailabilityRow struct {
	SeatOrdinal int32 `json:"seatOrdinal"`
	Status      int16 `json:"status"`
	Sellable    bool  `json:"sellable"`
}

// ListEventSeatsForAvailability: the Phase 2 DB-scan path for
// GET /events/{id}/availability — Index Only Scan on event_seats_cover_idx.
// Superseded by the Redis-backed projector path in Phase 7, DB fallback
// kept for when Redis is cold/down.
func (q *Queries) ListEventSeatsForAvailability(ctx context.Context, eventID int64) ([]ListEventSeatsForAvailabilityRow, error) {
	rows, err := q.db.Query(ctx, listEventSeatsForAvailability, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventSeatsForAvailabilityRow
	for rows.Next() {
		var i ListEventSeatsForAvailabilityRow
		if err := rows.Scan(&i.SeatOrdinal, &i.Status, &i.Sellable); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT event_id, venue_id, artist, title, starts_at, onsale_at, home_region, status, layout_version, created_at FROM events
WHERE ($1::text = '' OR title ILIKE '%' || $1 || '%' OR artist ILIKE '%' || $1 || '%')
  AND ($2::bigint = 0 OR event_id > $2)
ORDER BY event_id
LIMIT $3
`

type ListEventsParams struct {
	Column1 string `json:"column1"`
	Column2 int64  `json:"column2"`
	Limit   int32  `json:"limit"`
}

// ListEvents: simple keyset pagination by event_id, optional trigram search
// over title/artist (pg_trgm GIN-accelerated ILIKE — docs/plan.md decision #8).
func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.Column1, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.EventID,
			&i.VenueID,
			&i.Artist,
			&i.Title,
			&i.StartsAt,
			&i.OnsaleAt,
			&i.HomeRegion,
			&i.Status,
			&i.LayoutVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVenueSeatsOrdered = `-- name: ListVenueSeatsOrdered :many
SELECT
    s.section_id, s.name AS section_name, s.tier AS section_tier,
    s.display_order AS section_display_order, s.closed AS section_closed,
    r.row_id, r.label AS row_label, r.display_order AS row_display_order,
    st.seat_id, st.seat_label, st.x_coord, st.y_coord
FROM sections s
JOIN seat_rows r ON r.section_id = s.section_id
JOIN seats st ON st.row_id = r.row_id
WHERE s.venue_id = $1
ORDER BY s.display_order, r.display_order, st.seat_label
`

type ListVenueSeatsOrderedRow struct {
	SectionID           int64  `json:"sectionId"`
	SectionName         string `json:"sectionName"`
	SectionTier         string `json:"sectionTier"`
	SectionDisplayOrder int32  `json:"sectionDisplayOrder"`
	SectionClosed       bool   `json:"sectionClosed"`
	RowID               int64  `json:"rowId"`
	RowLabel            string `json:"rowLabel"`
	RowDisplayOrder     int32  `json:"rowDisplayOrder"`
	SeatID              int64  `json:"seatId"`
	SeatLabel           string `json:"seatLabel"`
	XCoord              int32  `json:"xCoord"`
	YCoord              int32  `json:"yCoord"`
}

// ListVenueSeatsOrdered drives both cmd/event-publisher's ordinal
// assignment and layout.json/seats.bin rendering from the SAME walk, in the
// SAME order (section.display_order, row.display_order, seat_label) — so
// the DB's ordinal assignment and the static layout files can never
// disagree (docs/plan.md "Event publish pipeline").
func (q *Queries) ListVenueSeatsOrdered(ctx context.Context, venueID int64) ([]ListVenueSeatsOrderedRow, error) {
	rows, err := q.db.Query(ctx, listVenueSeatsOrdered, venueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVenueSeatsOrderedRow
	for rows.Next() {
		var i ListVenueSeatsOrderedRow
		if err := rows.Scan(
			&i.SectionID,
			&i.SectionName,
			&i.SectionTier,
			&i.SectionDisplayOrder,
			&i.SectionClosed,
			&i.RowID,
			&i.RowLabel,
			&i.RowDisplayOrder,
			&i.SeatID,
			&i.SeatLabel,
			&i.XCoord,
			&i.YCoord,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEventOnSale = `-- name: SetEventOnSale :exec
UPDATE events SET status = 'ON_SALE' WHERE event_id = $1
`

func (q *Queries) SetEventOnSale(ctx context.Context, eventID int64) error {
	_, err := q.db.Exec(ctx, setEventOnSale, eventID)
	return err
}
