// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// BulkInsertEventSeats: cmd/event-publisher's population step, via pgx's
	// CopyFrom (sqlc :copyfrom) rather than one INSERT per row — the walk is
	// 30,000+ rows for a large venue.
	BulkInsertEventSeats(ctx context.Context, arg []BulkInsertEventSeatsParams) (int64, error)
	// CountAvailableSeats: fine at catalog-listing scale (one query per event in
	// a <=100-row page); revisit with a materialized per-event counter only if
	// this becomes a measured bottleneck.
	CountAvailableSeats(ctx context.Context, eventID int64) (int64, error)
	CountEventSeats(ctx context.Context, eventID int64) (int64, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateEventPriceTier(ctx context.Context, arg CreateEventPriceTierParams) error
	CreateSeat(ctx context.Context, arg CreateSeatParams) (Seat, error)
	CreateSeatRow(ctx context.Context, arg CreateSeatRowParams) (SeatRow, error)
	CreateSection(ctx context.Context, arg CreateSectionParams) (Section, error)
	// Phase 2: venue-template writes (used by scripts/seed-venue) and the
	// catalog/availability/pricing read path. Hold/release/confirm CAS queries
	// land in Phase 3 alongside internal/inventory.
	CreateVenue(ctx context.Context, arg CreateVenueParams) (Venue, error)
	GetEvent(ctx context.Context, eventID int64) (Event, error)
	GetVenue(ctx context.Context, venueID int64) (Venue, error)
	// A section counts as closed for this event only once every seat in it is
	// unsellable — closedSections is denormalized FROM event_seats.sellable,
	// never the other way round (docs/plan.md, fixed gap #2).
	ListClosedSectionsForEvent(ctx context.Context, eventID int64) ([]int64, error)
	ListEventPriceTiers(ctx context.Context, eventID int64) ([]EventPriceTier, error)
	// ListEventSeatsForAvailability: the Phase 2 DB-scan path for
	// GET /events/{id}/availability — Index Only Scan on event_seats_cover_idx.
	// Superseded by the Redis-backed projector path in Phase 7, DB fallback
	// kept for when Redis is cold/down.
	ListEventSeatsForAvailability(ctx context.Context, eventID int64) ([]ListEventSeatsForAvailabilityRow, error)
	// ListEvents: simple keyset pagination by event_id, optional trigram search
	// over title/artist (pg_trgm GIN-accelerated ILIKE — docs/plan.md decision #8).
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	// ListVenueSeatsOrdered drives both cmd/event-publisher's ordinal
	// assignment and layout.json/seats.bin rendering from the SAME walk, in the
	// SAME order (section.display_order, row.display_order, seat_label) — so
	// the DB's ordinal assignment and the static layout files can never
	// disagree (docs/plan.md "Event publish pipeline").
	ListVenueSeatsOrdered(ctx context.Context, venueID int64) ([]ListVenueSeatsOrderedRow, error)
	MinEventPriceCents(ctx context.Context, eventID int64) (int32, error)
	SetEventOnSale(ctx context.Context, eventID int64) error
}

var _ Querier = (*Queries)(nil)
