// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// AcquireHold: the arbiter. `sellable` gates the CAS so a structurally
	// unsellable seat can never be held; the status predicate is passive
	// expiry — the WHERE clause IS the guarantee, not a timer.
	AcquireHold(ctx context.Context, arg AcquireHoldParams) ([]AcquireHoldRow, error)
	// BulkInsertEventSeats: cmd/event-publisher's population step, via pgx's
	// CopyFrom (sqlc :copyfrom) rather than one INSERT per row — the walk is
	// 30,000+ rows for a large venue.
	BulkInsertEventSeats(ctx context.Context, arg []BulkInsertEventSeatsParams) (int64, error)
	// ConfirmSeats: the single most important statement in the whole system.
	// fence_token equality (not >=, see fixed gap #3) is the RedLock-question
	// answer — a zombie holder whose hold was reclaimed and re-issued fails
	// here even if it somehow still holds a matching hold_id.
	// Two single-arg unnest()s zipped by WITH ORDINALITY, not the two-array
	// unnest(a, b) form — sqlc's own function catalog doesn't model that
	// overload even though Postgres itself supports it since 9.4.
	ConfirmSeats(ctx context.Context, arg ConfirmSeatsParams) (int64, error)
	// CountAvailableSeats: fine at catalog-listing scale (one query per event in
	// a <=100-row page); revisit with a materialized per-event counter only if
	// this becomes a measured bottleneck.
	CountAvailableSeats(ctx context.Context, eventID int64) (int64, error)
	CountEventSeats(ctx context.Context, eventID int64) (int64, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateEventPriceTier(ctx context.Context, arg CreateEventPriceTierParams) error
	CreateSeat(ctx context.Context, arg CreateSeatParams) (Seat, error)
	CreateSeatRow(ctx context.Context, arg CreateSeatRowParams) (SeatRow, error)
	CreateSection(ctx context.Context, arg CreateSectionParams) (Section, error)
	// Phase 2: venue-template writes (used by scripts/seed-venue) and the
	// catalog/availability/pricing read path. Hold/release/confirm CAS queries
	// land in Phase 3 alongside internal/inventory.
	CreateVenue(ctx context.Context, arg CreateVenueParams) (Venue, error)
	// ExtendHold: called at payment initiation. rowcount < len(seats) means the
	// hold already lapsed — the saga must abort BEFORE charging.
	ExtendHold(ctx context.Context, arg ExtendHoldParams) (int64, error)
	GetEvent(ctx context.Context, eventID int64) (Event, error)
	// Phase 3: the correctness core (docs/plan.md "The correctness core").
	// Callers MUST pre-sort seat_ids ascending (and fences alongside them for
	// ConfirmSeats) — that ordering is what makes deadlock between two
	// concurrent multi-seat CAS statements structurally impossible, not just
	// unlikely (fixed gap #8).
	GetSeatIDsByOrdinals(ctx context.Context, arg GetSeatIDsByOrdinalsParams) ([]GetSeatIDsByOrdinalsRow, error)
	// GetSeatsByHoldID: the lookup GET/DELETE /holds/{id} and POST
	// /holds/{id}/extend need — no separate `holds` table exists, so a hold's
	// seats are found by hold_id alone via event_seats_hold_id_idx.
	GetSeatsByHoldID(ctx context.Context, holdID pgtype.UUID) ([]GetSeatsByHoldIDRow, error)
	GetVenue(ctx context.Context, venueID int64) (Venue, error)
	InsertDomainEvent(ctx context.Context, arg InsertDomainEventParams) error
	InsertHoldsAudit(ctx context.Context, arg InsertHoldsAuditParams) error
	// ListAvailableForBestAvailable: candidate seats for the contiguous-run
	// scan (internal/inventory.BestAvailable) — row_id is included because
	// ordinals are contiguous ACROSS a whole section, not just within one row
	// (decision #2), so a run must be broken at a row boundary in Go, not just
	// by ordinal adjacency.
	ListAvailableForBestAvailable(ctx context.Context, arg ListAvailableForBestAvailableParams) ([]ListAvailableForBestAvailableRow, error)
	// A section counts as closed for this event only once every seat in it is
	// unsellable — closedSections is denormalized FROM event_seats.sellable,
	// never the other way round (docs/plan.md, fixed gap #2).
	ListClosedSectionsForEvent(ctx context.Context, eventID int64) ([]int64, error)
	ListEventPriceTiers(ctx context.Context, eventID int64) ([]EventPriceTier, error)
	// ListEventSeatsForAvailability: the Phase 2 DB-scan path for
	// GET /events/{id}/availability — Index Only Scan on event_seats_cover_idx.
	// Superseded by the Redis-backed projector path in Phase 7, DB fallback
	// kept for when Redis is cold/down.
	ListEventSeatsForAvailability(ctx context.Context, eventID int64) ([]ListEventSeatsForAvailabilityRow, error)
	// ListEvents: simple keyset pagination by event_id, optional trigram search
	// over title/artist (pg_trgm GIN-accelerated ILIKE — docs/plan.md decision #8).
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	// ListExpiredHolds: cmd/hold-reaper's scan target — the ACTIVE release
	// (UX freshness only; passive expiry in the CAS predicate is the actual
	// correctness guarantee, docs/plan.md decision #2).
	ListExpiredHolds(ctx context.Context) ([]ListExpiredHoldsRow, error)
	ListSeatIDsForHold(ctx context.Context, arg ListSeatIDsForHoldParams) ([]int64, error)
	ListUnpublishedDomainEvents(ctx context.Context, rowLimit int32) ([]ListUnpublishedDomainEventsRow, error)
	// ListVenueSeatsOrdered drives both cmd/event-publisher's ordinal
	// assignment and layout.json/seats.bin rendering from the SAME walk, in the
	// SAME order (section.display_order, row.display_order, seat_label) — so
	// the DB's ordinal assignment and the static layout files can never
	// disagree (docs/plan.md "Event publish pipeline").
	ListVenueSeatsOrdered(ctx context.Context, venueID int64) ([]ListVenueSeatsOrderedRow, error)
	MarkDomainEventPublished(ctx context.Context, eventID uuid.UUID) error
	MinEventPriceCents(ctx context.Context, eventID int64) (int32, error)
	// ReleaseHold: idempotent by construction — rowcount 0 is success (the
	// hold was already gone), not an error.
	ReleaseHold(ctx context.Context, arg ReleaseHoldParams) (int64, error)
	SetEventOnSale(ctx context.Context, eventID int64) error
}

var _ Querier = (*Queries)(nil)
