# The Lambda-lith: one function running the same chi router as cmd/server,
# via cmd/lambda's aws-lambda-go-api-proxy adapter. `make build-lambda`
# produces build/bootstrap.zip before `terraform apply` — CI runs it as a
# pipeline step (see docs/... §11); it is never generated by Terraform itself.

resource "aws_iam_role" "lambda" {
  name = "${var.name_prefix}-lambda-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "lambda.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })
}

# Covers CloudWatch Logs + ENI create/delete for VPC-attached Lambdas — no
# separate AWSLambdaBasicExecutionRole needed, this one supersets it.
resource "aws_iam_role_policy_attachment" "vpc_access" {
  role       = aws_iam_role.lambda.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
}

# Least-priv beyond the managed policy: only the secret this function needs,
# only the photos bucket's objects (PutObject for presigning, GetObject for
# confirm's HeadObject check — s3:GetObject also covers HeadObject).
resource "aws_iam_role_policy" "lambda_app" {
  name = "${var.name_prefix}-lambda-app-policy"
  role = aws_iam_role.lambda.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect   = "Allow"
        Action   = ["secretsmanager:GetSecretValue"]
        Resource = var.db_secret_arn
      },
      {
        Effect   = "Allow"
        Action   = ["s3:PutObject", "s3:GetObject"]
        Resource = "${var.photos_bucket_arn}/*"
      },
    ]
  })
}

resource "aws_lambda_function" "api" {
  function_name = "${var.name_prefix}-api"
  role          = aws_iam_role.lambda.arn

  filename         = "${path.module}/build/bootstrap.zip"
  source_code_hash = filebase64sha256("${path.module}/build/bootstrap.zip")

  runtime       = "provided.al2023"
  architectures = ["arm64"]
  handler       = "bootstrap" # ignored by the custom runtime, AWS still requires a value

  timeout     = 10
  memory_size = 256

  vpc_config {
    subnet_ids         = var.private_subnet_ids
    security_group_ids = [var.lambda_security_group_id]
  }

  environment {
    variables = var.environment
  }
}
